/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaseEventCreateQueryBulkEntryResourceObjectAttributes } from './baseEventCreateQueryBulkEntryResourceObjectAttributes';
import { EventEnum } from './eventEnum';
export class BaseEventCreateQueryBulkEntryResourceObject {
    'type': EventEnum | 'event';
    'attributes': BaseEventCreateQueryBulkEntryResourceObjectAttributes;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "EventEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "BaseEventCreateQueryBulkEntryResourceObjectAttributes"
        }    ];

    static getAttributeTypeMap() {
        return BaseEventCreateQueryBulkEntryResourceObject.attributeTypeMap;
    }
}

export namespace BaseEventCreateQueryBulkEntryResourceObject {
}
