/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignEnum } from './campaignEnum';
import { CampaignPartialUpdateQueryResourceObjectAttributes } from './campaignPartialUpdateQueryResourceObjectAttributes';

export class CampaignPartialUpdateQueryResourceObject {
    'attributes': CampaignPartialUpdateQueryResourceObjectAttributes;
    'type': CampaignEnum;
    /**
    * The campaign ID to be retrieved
    */
    'id': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "CampaignPartialUpdateQueryResourceObjectAttributes"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CampaignEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CampaignPartialUpdateQueryResourceObject.attributeTypeMap;
    }
}

export namespace CampaignPartialUpdateQueryResourceObject {
}
