/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignCloneQueryResourceObjectAttributes } from './campaignCloneQueryResourceObjectAttributes';
import { CampaignEnum } from './campaignEnum';

export class CampaignCloneQueryResourceObject {
    'attributes': CampaignCloneQueryResourceObjectAttributes;
    'type': CampaignEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "CampaignCloneQueryResourceObjectAttributes"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CampaignEnum"
        }    ];

    static getAttributeTypeMap() {
        return CampaignCloneQueryResourceObject.attributeTypeMap;
    }
}

export namespace CampaignCloneQueryResourceObject {
}
