/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignSendJobEnum } from './campaignSendJobEnum';
import { CampaignSendJobPartialUpdateQueryResourceObjectAttributes } from './campaignSendJobPartialUpdateQueryResourceObjectAttributes';

export class CampaignSendJobPartialUpdateQueryResourceObject {
    'type': CampaignSendJobEnum;
    /**
    * The ID of the currently sending campaign to cancel or revert
    */
    'id': string;
    'attributes': CampaignSendJobPartialUpdateQueryResourceObjectAttributes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CampaignSendJobEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "CampaignSendJobPartialUpdateQueryResourceObjectAttributes"
        }    ];

    static getAttributeTypeMap() {
        return CampaignSendJobPartialUpdateQueryResourceObject.attributeTypeMap;
    }
}

export namespace CampaignSendJobPartialUpdateQueryResourceObject {
}
