/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignsEmailTrackingOptions } from './campaignsEmailTrackingOptions';
import { CampaignsEmailTrackingOptionsCustomTrackingParamsInner } from './campaignsEmailTrackingOptionsCustomTrackingParamsInner';
import { CampaignsSMSTrackingOptions } from './campaignsSMSTrackingOptions';
export type CampaignResponseObjectResourceAttributesTrackingOptions = CampaignsEmailTrackingOptions | CampaignsSMSTrackingOptions;
