/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CartValueEnum } from './cartValueEnum';
import { CartValueProperties } from './cartValueProperties';
export class CartValue {
    'id'?: string | null;
    'type': CartValueEnum | 'cart_value';
    'properties'?: CartValueProperties;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CartValueEnum"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "CartValueProperties"
        }    ];

    static getAttributeTypeMap() {
        return CartValue.attributeTypeMap;
    }
}

export namespace CartValue {
}
