/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CatalogCategoryCreateQueryResourceObjectAttributes } from './catalogCategoryCreateQueryResourceObjectAttributes';
import { CatalogCategoryCreateQueryResourceObjectRelationships } from './catalogCategoryCreateQueryResourceObjectRelationships';
import { CatalogCategoryEnum } from './catalogCategoryEnum';

export class CatalogCategoryCreateQueryResourceObject {
    'type': CatalogCategoryEnum | 'catalog-category';
    'attributes': CatalogCategoryCreateQueryResourceObjectAttributes;
    'relationships'?: CatalogCategoryCreateQueryResourceObjectRelationships;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CatalogCategoryEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "CatalogCategoryCreateQueryResourceObjectAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "CatalogCategoryCreateQueryResourceObjectRelationships"
        }    ];

    static getAttributeTypeMap() {
        return CatalogCategoryCreateQueryResourceObject.attributeTypeMap;
    }
}

export namespace CatalogCategoryCreateQueryResourceObject {
}
