/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CatalogItemUpdateQueryResourceObjectAttributes {
    /**
    * A description of the catalog item.
    */
    'description'?: string;
    /**
    * The title of the catalog item.
    */
    'title'?: string;
    /**
    * URL pointing to the location of the catalog item on your website.
    */
    'url'?: string;
    /**
    * This field can be used to set the price on the catalog item, which is what gets displayed for the item when included in emails. For most price-update use cases, you will also want to update the `price` on any child variants, using the [Update Catalog Variant Endpoint](https://developers.klaviyo.com/en/reference/update_catalog_variant).
    */
    'price'?: number;
    /**
    * Flat JSON blob to provide custom metadata about the catalog item. May not exceed 100kb.
    */
    'customMetadata'?: object;
    /**
    * URL pointing to the location of a full image of the catalog item.
    */
    'imageFullUrl'?: string;
    /**
    * Boolean value indicating whether the catalog item is published.
    */
    'published'?: boolean;
    /**
    * List of URLs pointing to the locations of images of the catalog item.
    */
    'images'?: Array<string>;
    /**
    * URL pointing to the location of an image thumbnail of the catalog item
    */
    'imageThumbnailUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "customMetadata",
            "baseName": "custom_metadata",
            "type": "object"
        },
        {
            "name": "imageFullUrl",
            "baseName": "image_full_url",
            "type": "string"
        },
        {
            "name": "published",
            "baseName": "published",
            "type": "boolean"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<string>"
        },
        {
            "name": "imageThumbnailUrl",
            "baseName": "image_thumbnail_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CatalogItemUpdateQueryResourceObjectAttributes.attributeTypeMap;
    }
}

