/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CatalogItemCreateQueryResourceObjectAttributes {
    /**
    * The ID of the catalog item in an external system.
    */
    'externalId': string;
    /**
    * The integration type. Currently only \"$custom\" is supported.
    */
    'integrationType'?: CatalogItemCreateQueryResourceObjectAttributes.IntegrationTypeEnum | '$custom' = CatalogItemCreateQueryResourceObjectAttributes.IntegrationTypeEnum.Custom;
    /**
    * The title of the catalog item.
    */
    'title': string;
    /**
    * This field can be used to set the price on the catalog item, which is what gets displayed for the item when included in emails. For most price-update use cases, you will also want to update the `price` on any child variants, using the [Update Catalog Variant Endpoint](https://developers.klaviyo.com/en/reference/update_catalog_variant).
    */
    'price'?: number;
    /**
    * The type of catalog. Currently only \"$default\" is supported.
    */
    'catalogType'?: string = '$default';
    /**
    * A description of the catalog item.
    */
    'description': string;
    /**
    * URL pointing to the location of the catalog item on your website.
    */
    'url': string;
    /**
    * URL pointing to the location of a full image of the catalog item.
    */
    'imageFullUrl'?: string;
    /**
    * URL pointing to the location of an image thumbnail of the catalog item
    */
    'imageThumbnailUrl'?: string;
    /**
    * List of URLs pointing to the locations of images of the catalog item.
    */
    'images'?: Array<string>;
    /**
    * Flat JSON blob to provide custom metadata about the catalog item. May not exceed 100kb.
    */
    'customMetadata'?: object;
    /**
    * Boolean value indicating whether the catalog item is published.
    */
    'published'?: boolean = true;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "integrationType",
            "baseName": "integration_type",
            "type": "CatalogItemCreateQueryResourceObjectAttributes.IntegrationTypeEnum"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "catalogType",
            "baseName": "catalog_type",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "imageFullUrl",
            "baseName": "image_full_url",
            "type": "string"
        },
        {
            "name": "imageThumbnailUrl",
            "baseName": "image_thumbnail_url",
            "type": "string"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<string>"
        },
        {
            "name": "customMetadata",
            "baseName": "custom_metadata",
            "type": "object"
        },
        {
            "name": "published",
            "baseName": "published",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CatalogItemCreateQueryResourceObjectAttributes.attributeTypeMap;
    }
}

export namespace CatalogItemCreateQueryResourceObjectAttributes {
    export enum IntegrationTypeEnum {
        Custom = <any> '$custom'
    }
}
