/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CatalogVariantBulkUpdateJobEnum } from './catalogVariantBulkUpdateJobEnum';
import { CatalogVariantUpdateJobCreateQueryResourceObjectAttributes } from './catalogVariantUpdateJobCreateQueryResourceObjectAttributes';
export class CatalogVariantUpdateJobCreateQueryResourceObject {
    'type': CatalogVariantBulkUpdateJobEnum | 'catalog-variant-bulk-update-job';
    'attributes': CatalogVariantUpdateJobCreateQueryResourceObjectAttributes;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CatalogVariantBulkUpdateJobEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "CatalogVariantUpdateJobCreateQueryResourceObjectAttributes"
        }    ];

    static getAttributeTypeMap() {
        return CatalogVariantUpdateJobCreateQueryResourceObject.attributeTypeMap;
    }
}

export namespace CatalogVariantUpdateJobCreateQueryResourceObject {
}
