/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CatalogItemCreateJobResponseObjectResourceAttributes } from './catalogItemCreateJobResponseObjectResourceAttributes';
import { CatalogVariantBulkDeleteJobEnum } from './catalogVariantBulkDeleteJobEnum';
import { ObjectLinks } from './objectLinks';

export class CatalogVariantDeleteJobResponseObjectResource {
    'type': CatalogVariantBulkDeleteJobEnum;
    'attributes': CatalogItemCreateJobResponseObjectResourceAttributes;
    'links': ObjectLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CatalogVariantBulkDeleteJobEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "CatalogItemCreateJobResponseObjectResourceAttributes"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return CatalogVariantDeleteJobResponseObjectResource.attributeTypeMap;
    }
}

export namespace CatalogVariantDeleteJobResponseObjectResource {
}
