/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CatalogItemBulkUpdateJobEnum } from './catalogItemBulkUpdateJobEnum';
import { CatalogItemUpdateJobCreateQueryResourceObjectAttributes } from './catalogItemUpdateJobCreateQueryResourceObjectAttributes';

export class CatalogItemUpdateJobCreateQueryResourceObject {
    'type': CatalogItemBulkUpdateJobEnum | 'catalog-item-bulk-update-job';
    'attributes': CatalogItemUpdateJobCreateQueryResourceObjectAttributes;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CatalogItemBulkUpdateJobEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "CatalogItemUpdateJobCreateQueryResourceObjectAttributes"
        }    ];

    static getAttributeTypeMap() {
        return CatalogItemUpdateJobCreateQueryResourceObject.attributeTypeMap;
    }
}

export namespace CatalogItemUpdateJobCreateQueryResourceObject {
}
