/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CollectionLinks {
    'self': string;
    'first'?: string;
    'last'?: string;
    'prev'?: string;
    'next'?: string;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "self",
            "baseName": "self",
            "type": "string"
        },
        {
            "name": "first",
            "baseName": "first",
            "type": "string"
        },
        {
            "name": "last",
            "baseName": "last",
            "type": "string"
        },
        {
            "name": "prev",
            "baseName": "prev",
            "type": "string"
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CollectionLinks.attributeTypeMap;
    }
}

