/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConstantPropertyMappingValue } from './constantPropertyMappingValue';
export class ConstantPropertyMapping {
    /**
    * Property ID. Must be a positive integer.
    */
    'id': number;
    /**
    * String literal for serialization
    */
    'type': ConstantPropertyMapping.TypeEnum | 'constant';
    'value': ConstantPropertyMappingValue;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ConstantPropertyMapping.TypeEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ConstantPropertyMappingValue"
        }    ];

    static getAttributeTypeMap() {
        return ConstantPropertyMapping.attributeTypeMap;
    }
}

export namespace ConstantPropertyMapping {
    export enum TypeEnum {
        Constant = <any> 'constant'
    }
}
