/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContentExperimentActionDataMainAction } from './contentExperimentActionDataMainAction';
export class ContentExperimentActionDataCurrentExperiment {
    /**
    * Not allowed on create.
    */
    'id'?: string | null;
    'name'?: string | null;
    'variations': Array<ContentExperimentActionDataMainAction>;
    'allocations'?: object | null;
    'started'?: Date | null;
    /**
    * The metric to use to determine the winner of the content experiment     action.
    */
    'winnerMetric'?: ContentExperimentActionDataCurrentExperiment.WinnerMetricEnum | 'click-rate' | 'open-rate' | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "variations",
            "baseName": "variations",
            "type": "Array<ContentExperimentActionDataMainAction>"
        },
        {
            "name": "allocations",
            "baseName": "allocations",
            "type": "object"
        },
        {
            "name": "started",
            "baseName": "started",
            "type": "Date"
        },
        {
            "name": "winnerMetric",
            "baseName": "winner_metric",
            "type": "ContentExperimentActionDataCurrentExperiment.WinnerMetricEnum"
        }    ];

    static getAttributeTypeMap() {
        return ContentExperimentActionDataCurrentExperiment.attributeTypeMap;
    }
}

export namespace ContentExperimentActionDataCurrentExperiment {
    export enum WinnerMetricEnum {
        ClickRate = <any> 'click-rate',
        OpenRate = <any> 'open-rate'
    }
}
