/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContentExperimentActionData } from './contentExperimentActionData';
import { Link } from './link';
export class ContentExperimentAction {
    /**
    * The real ID of an action. Not allowed on create.
    */
    'id'?: string | null;
    /**
    * A temporary ID to use only during a create operation. Existing actions should use the id field.
    */
    'temporaryId'?: string | null;
    'type': ContentExperimentAction.TypeEnum | 'content-experiment';
    'links'?: Link;
    'data': ContentExperimentActionData;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "temporaryId",
            "baseName": "temporary_id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ContentExperimentAction.TypeEnum"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Link"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "ContentExperimentActionData"
        }    ];

    static getAttributeTypeMap() {
        return ContentExperimentAction.attributeTypeMap;
    }
}

export namespace ContentExperimentAction {
    export enum TypeEnum {
        ContentExperiment = <any> 'content-experiment'
    }
}
