/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ConversationResponseObjectResourceAttributes {
    /**
    * The messaging channel of the conversation.
    */
    'channel': ConversationResponseObjectResourceAttributes.ChannelEnum | 'instagram' | 'sms' | 'whatsapp';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "ConversationResponseObjectResourceAttributes.ChannelEnum"
        }    ];

    static getAttributeTypeMap() {
        return ConversationResponseObjectResourceAttributes.attributeTypeMap;
    }
}

export namespace ConversationResponseObjectResourceAttributes {
    export enum ChannelEnum {
        Instagram = <any> 'instagram',
        Sms = <any> 'sms',
        Whatsapp = <any> 'whatsapp'
    }
}
