/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DataSourceRecordBulkCreateJobCreateQueryResourceObjectRelationships } from './dataSourceRecordBulkCreateJobCreateQueryResourceObjectRelationships';
import { DataSourceRecordCreateJobCreateQueryResourceObjectAttributes } from './dataSourceRecordCreateJobCreateQueryResourceObjectAttributes';
import { DataSourceRecordCreateJobEnum } from './dataSourceRecordCreateJobEnum';
export class DataSourceRecordCreateJobCreateQueryResourceObject {
    'type': DataSourceRecordCreateJobEnum | 'data-source-record-create-job';
    'attributes': DataSourceRecordCreateJobCreateQueryResourceObjectAttributes;
    'relationships'?: DataSourceRecordBulkCreateJobCreateQueryResourceObjectRelationships;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "DataSourceRecordCreateJobEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "DataSourceRecordCreateJobCreateQueryResourceObjectAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "DataSourceRecordBulkCreateJobCreateQueryResourceObjectRelationships"
        }    ];

    static getAttributeTypeMap() {
        return DataSourceRecordCreateJobCreateQueryResourceObject.attributeTypeMap;
    }
}

export namespace DataSourceRecordCreateJobCreateQueryResourceObject {
}
