/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorMessages } from './errorMessages';
export class DateProperties {
    'displayDevice'?: Array<DateProperties.DisplayDeviceEnum> | Array<'both' | 'desktop' | 'mobile'>;
    'propertyName': string;
    'label'?: string | null;
    'showLabel'?: boolean = false;
    'placeholder'?: string | null;
    'required'?: boolean | null = false;
    'errorMessages'?: ErrorMessages;
    'dateFormat'?: string = 'MM/DD';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "displayDevice",
            "baseName": "display_device",
            "type": "Array<DateProperties.DisplayDeviceEnum>"
        },
        {
            "name": "propertyName",
            "baseName": "property_name",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "showLabel",
            "baseName": "show_label",
            "type": "boolean"
        },
        {
            "name": "placeholder",
            "baseName": "placeholder",
            "type": "string"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        },
        {
            "name": "errorMessages",
            "baseName": "error_messages",
            "type": "ErrorMessages"
        },
        {
            "name": "dateFormat",
            "baseName": "date_format",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DateProperties.attributeTypeMap;
    }
}

export namespace DateProperties {
    export enum DisplayDeviceEnum {
        Both = <any> 'both',
        Desktop = <any> 'desktop',
        Mobile = <any> 'mobile'
    }
}
