/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExplicitlyReachableEnum } from './explicitlyReachableEnum';
import { ExplicitlyReachableFiltersInner } from './explicitlyReachableFiltersInner';
export class ExplicitlyReachable {
    'reachableStatus': ExplicitlyReachableEnum | 'explicitly_reachable';
    'filters': Array<ExplicitlyReachableFiltersInner>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reachableStatus",
            "baseName": "reachable_status",
            "type": "ExplicitlyReachableEnum"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<ExplicitlyReachableFiltersInner>"
        }    ];

    static getAttributeTypeMap() {
        return ExplicitlyReachable.attributeTypeMap;
    }
}

export namespace ExplicitlyReachable {
}
