/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlowDefinition } from './flowDefinition';
import { FlowV2ResponseObjectResourceAttributes } from './flowV2ResponseObjectResourceAttributes';
export class FlowV2ResponseObjectResourceExtendedAttributes extends FlowV2ResponseObjectResourceAttributes {
    'definition'?: FlowDefinition;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "definition",
            "baseName": "definition",
            "type": "FlowDefinition"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(FlowV2ResponseObjectResourceExtendedAttributes.attributeTypeMap);
    }
}

export namespace FlowV2ResponseObjectResourceExtendedAttributes {
}
