/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UnionFilter } from './unionFilter';
export class FlowPushNotification {
    'title'?: string | null;
    'body': string;
    'sound'?: boolean = false;
    'badge'?: boolean = false;
    /**
    * The id of an ImageAsset. If provided, this will take precedence over a dynamic_image.
    */
    'imageId'?: string | null;
    /**
    * A dynamic image asset to include in the push notification.
    */
    'dynamicImage'?: string | null;
    /**
    * See PushLinkAction in app.  This is not a flow action, but the literal action that should be taken when the push notification is tapped.
    */
    'onOpen'?: FlowPushNotification.OnOpenEnum | 'home' | 'link' = FlowPushNotification.OnOpenEnum.Home;
    'iosLink'?: string | null;
    'androidLink'?: string | null;
    /**
    * The type of push notification to send.
    */
    'pushType'?: FlowPushNotification.PushTypeEnum | 'silent' | 'standard' | null;
    'kvPairs'?: object | null;
    'conversionMetricId'?: string | null;
    'smartSendingEnabled'?: boolean = true;
    'additionalFilters'?: UnionFilter;
    'name'?: string | null;
    'id'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "sound",
            "baseName": "sound",
            "type": "boolean"
        },
        {
            "name": "badge",
            "baseName": "badge",
            "type": "boolean"
        },
        {
            "name": "imageId",
            "baseName": "image_id",
            "type": "string"
        },
        {
            "name": "dynamicImage",
            "baseName": "dynamic_image",
            "type": "string"
        },
        {
            "name": "onOpen",
            "baseName": "on_open",
            "type": "FlowPushNotification.OnOpenEnum"
        },
        {
            "name": "iosLink",
            "baseName": "ios_link",
            "type": "string"
        },
        {
            "name": "androidLink",
            "baseName": "android_link",
            "type": "string"
        },
        {
            "name": "pushType",
            "baseName": "push_type",
            "type": "FlowPushNotification.PushTypeEnum"
        },
        {
            "name": "kvPairs",
            "baseName": "kv_pairs",
            "type": "object"
        },
        {
            "name": "conversionMetricId",
            "baseName": "conversion_metric_id",
            "type": "string"
        },
        {
            "name": "smartSendingEnabled",
            "baseName": "smart_sending_enabled",
            "type": "boolean"
        },
        {
            "name": "additionalFilters",
            "baseName": "additional_filters",
            "type": "UnionFilter"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FlowPushNotification.attributeTypeMap;
    }
}

export namespace FlowPushNotification {
    export enum OnOpenEnum {
        Home = <any> 'home',
        Link = <any> 'link'
    }
    export enum PushTypeEnum {
        Silent = <any> 'silent',
        Standard = <any> 'standard'
    }
}
