/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignValuesRequestDTOResourceObjectAttributesTimeframe } from './campaignValuesRequestDTOResourceObjectAttributesTimeframe';
export class FormValuesRequestDTOResourceObjectAttributes {
    /**
    * List of statistics to query for. All rate statistics will be returned in fractional form [0.0, 1.0]
    */
    'statistics': Array<FormValuesRequestDTOResourceObjectAttributes.StatisticsEnum> | Array<'closed_form' | 'closed_form_uniques' | 'qualified_form' | 'qualified_form_uniques' | 'submit_rate' | 'submits' | 'submitted_form_step' | 'submitted_form_step_uniques' | 'viewed_form' | 'viewed_form_step' | 'viewed_form_step_uniques' | 'viewed_form_uniques'>;
    'timeframe': CampaignValuesRequestDTOResourceObjectAttributesTimeframe;
    /**
    * List of attributes to group the data by. Allowed group-bys are form_version_id, form_id. If not passed in, the data will be grouped by form_id. If a group by has prerequisites, they must be passed in together. The prerequisites for form_version_id is form_id
    */
    'groupBy'?: Array<FormValuesRequestDTOResourceObjectAttributes.GroupByEnum> | Array<'form_id' | 'form_version_id'> | null;
    /**
    * API filter string used to filter the query. Allowed filters are form_version_id, form_id. Allowed operators are equals, any. Only one filter can be used per attribute, only AND can be used as a combination operator. Max of 100 messages per ANY filter.
    */
    'filter'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "statistics",
            "baseName": "statistics",
            "type": "Array<FormValuesRequestDTOResourceObjectAttributes.StatisticsEnum>"
        },
        {
            "name": "timeframe",
            "baseName": "timeframe",
            "type": "CampaignValuesRequestDTOResourceObjectAttributesTimeframe"
        },
        {
            "name": "groupBy",
            "baseName": "group_by",
            "type": "Array<FormValuesRequestDTOResourceObjectAttributes.GroupByEnum>"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FormValuesRequestDTOResourceObjectAttributes.attributeTypeMap;
    }
}

export namespace FormValuesRequestDTOResourceObjectAttributes {
    export enum StatisticsEnum {
        ClosedForm = <any> 'closed_form',
        ClosedFormUniques = <any> 'closed_form_uniques',
        QualifiedForm = <any> 'qualified_form',
        QualifiedFormUniques = <any> 'qualified_form_uniques',
        SubmitRate = <any> 'submit_rate',
        Submits = <any> 'submits',
        SubmittedFormStep = <any> 'submitted_form_step',
        SubmittedFormStepUniques = <any> 'submitted_form_step_uniques',
        ViewedForm = <any> 'viewed_form',
        ViewedFormStep = <any> 'viewed_form_step',
        ViewedFormStepUniques = <any> 'viewed_form_step_uniques',
        ViewedFormUniques = <any> 'viewed_form_uniques'
    }
    export enum GroupByEnum {
        Id = <any> 'form_id',
        VersionId = <any> 'form_version_id'
    }
}
