/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CatalogVariantResponseObjectResource } from './catalogVariantResponseObjectResource';
import { GetCatalogItemResponseCollectionCompoundDocumentDataInner } from './getCatalogItemResponseCollectionCompoundDocumentDataInner';

export class GetCatalogItemResponseCompoundDocument {
    'included'?: Array<CatalogVariantResponseObjectResource>;
    'data': GetCatalogItemResponseCollectionCompoundDocumentDataInner;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<CatalogVariantResponseObjectResource>"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "GetCatalogItemResponseCollectionCompoundDocumentDataInner"
        }    ];

    static getAttributeTypeMap() {
        return GetCatalogItemResponseCompoundDocument.attributeTypeMap;
    }
}

