/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetFlowActionResponseCollectionDataInnerAllOfRelationshipsFlow } from './getFlowActionResponseCollectionDataInnerAllOfRelationshipsFlow';
import { GetFlowActionResponseCollectionDataInnerAllOfRelationshipsFlowMessages } from './getFlowActionResponseCollectionDataInnerAllOfRelationshipsFlowMessages';

export class GetFlowActionResponseCollectionDataInnerAllOfRelationships {
    'flow'?: GetFlowActionResponseCollectionDataInnerAllOfRelationshipsFlow;
    'flowMessages'?: GetFlowActionResponseCollectionDataInnerAllOfRelationshipsFlowMessages;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flow",
            "baseName": "flow",
            "type": "GetFlowActionResponseCollectionDataInnerAllOfRelationshipsFlow"
        },
        {
            "name": "flowMessages",
            "baseName": "flow-messages",
            "type": "GetFlowActionResponseCollectionDataInnerAllOfRelationshipsFlowMessages"
        }    ];

    static getAttributeTypeMap() {
        return GetFlowActionResponseCollectionDataInnerAllOfRelationships.attributeTypeMap;
    }
}

