/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetFlowActionResponseDataAllOfRelationshipsFlow } from './getFlowActionResponseDataAllOfRelationshipsFlow';
import { GetFlowActionResponseDataAllOfRelationshipsFlowMessages } from './getFlowActionResponseDataAllOfRelationshipsFlowMessages';

export class GetFlowActionResponseDataAllOfRelationships {
    'flowMessages'?: GetFlowActionResponseDataAllOfRelationshipsFlowMessages;
    'flow'?: GetFlowActionResponseDataAllOfRelationshipsFlow;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flowMessages",
            "baseName": "flow-messages",
            "type": "GetFlowActionResponseDataAllOfRelationshipsFlowMessages"
        },
        {
            "name": "flow",
            "baseName": "flow",
            "type": "GetFlowActionResponseDataAllOfRelationshipsFlow"
        }    ];

    static getAttributeTypeMap() {
        return GetFlowActionResponseDataAllOfRelationships.attributeTypeMap;
    }
}

