/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CollectionLinks } from './collectionLinks';
import { GetListListResponseCollectionCompoundDocumentDataInner } from './getListListResponseCollectionCompoundDocumentDataInner';
import { TagResponseObjectResource } from './tagResponseObjectResource';
export class GetListListResponseCollectionCompoundDocument {
    'data': Array<GetListListResponseCollectionCompoundDocumentDataInner>;
    'links': CollectionLinks;
    'included'?: Array<TagResponseObjectResource>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<GetListListResponseCollectionCompoundDocumentDataInner>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "CollectionLinks"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<TagResponseObjectResource>"
        }    ];

    static getAttributeTypeMap() {
        return GetListListResponseCollectionCompoundDocument.attributeTypeMap;
    }
}

