/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetMappedMetricResponseCollectionCompoundDocumentDataInner } from './getMappedMetricResponseCollectionCompoundDocumentDataInner';
import { GetMappedMetricResponseCollectionCompoundDocumentIncludedInner } from './getMappedMetricResponseCollectionCompoundDocumentIncludedInner';
export class GetMappedMetricResponseCompoundDocument {
    'data': GetMappedMetricResponseCollectionCompoundDocumentDataInner;
    'included'?: Array<GetMappedMetricResponseCollectionCompoundDocumentIncludedInner>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "GetMappedMetricResponseCollectionCompoundDocumentDataInner"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<GetMappedMetricResponseCollectionCompoundDocumentIncludedInner>"
        }    ];

    static getAttributeTypeMap() {
        return GetMappedMetricResponseCompoundDocument.attributeTypeMap;
    }
}

