/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetProfileImportJobResponseCollectionCompoundDocumentDataInner } from './getProfileImportJobResponseCollectionCompoundDocumentDataInner';
import { ListResponseObjectResource } from './listResponseObjectResource';
export class GetProfileImportJobResponseCompoundDocument {
    'data': GetProfileImportJobResponseCollectionCompoundDocumentDataInner;
    'included'?: Array<ListResponseObjectResource>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "GetProfileImportJobResponseCollectionCompoundDocumentDataInner"
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<ListResponseObjectResource>"
        }    ];

    static getAttributeTypeMap() {
        return GetProfileImportJobResponseCompoundDocument.attributeTypeMap;
    }
}

