/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetSegmentListResponseCollectionCompoundDocumentDataInnerAllOfRelationships } from './getSegmentListResponseCollectionCompoundDocumentDataInnerAllOfRelationships';
import { ObjectLinks } from './objectLinks';
import { SegmentEnum } from './segmentEnum';
import { SegmentResponseObjectResource } from './segmentResponseObjectResource';
import { SegmentResponseObjectResourceAttributes } from './segmentResponseObjectResourceAttributes';

export class GetSegmentResponseCollectionDataInner extends SegmentResponseObjectResource {
    'relationships'?: GetSegmentListResponseCollectionCompoundDocumentDataInnerAllOfRelationships;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GetSegmentListResponseCollectionCompoundDocumentDataInnerAllOfRelationships"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(GetSegmentResponseCollectionDataInner.attributeTypeMap);
    }
}

export namespace GetSegmentResponseCollectionDataInner {
}
