/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetProfileResponseDataAllOfRelationshipsLists } from './getProfileResponseDataAllOfRelationshipsLists';
import { GetProfileResponseDataAllOfRelationshipsSegments } from './getProfileResponseDataAllOfRelationshipsSegments';
import { GetTagResponseCollectionDataInnerAllOfRelationshipsCampaigns } from './getTagResponseCollectionDataInnerAllOfRelationshipsCampaigns';
import { GetTagResponseCollectionDataInnerAllOfRelationshipsFlows } from './getTagResponseCollectionDataInnerAllOfRelationshipsFlows';
import { GetTagResponseCollectionDataInnerAllOfRelationshipsTagGroup } from './getTagResponseCollectionDataInnerAllOfRelationshipsTagGroup';

export class GetTagResponseCollectionDataInnerAllOfRelationships {
    'tagGroup'?: GetTagResponseCollectionDataInnerAllOfRelationshipsTagGroup;
    'lists'?: GetProfileResponseDataAllOfRelationshipsLists;
    'segments'?: GetProfileResponseDataAllOfRelationshipsSegments;
    'campaigns'?: GetTagResponseCollectionDataInnerAllOfRelationshipsCampaigns;
    'flows'?: GetTagResponseCollectionDataInnerAllOfRelationshipsFlows;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tagGroup",
            "baseName": "tag-group",
            "type": "GetTagResponseCollectionDataInnerAllOfRelationshipsTagGroup"
        },
        {
            "name": "lists",
            "baseName": "lists",
            "type": "GetProfileResponseDataAllOfRelationshipsLists"
        },
        {
            "name": "segments",
            "baseName": "segments",
            "type": "GetProfileResponseDataAllOfRelationshipsSegments"
        },
        {
            "name": "campaigns",
            "baseName": "campaigns",
            "type": "GetTagResponseCollectionDataInnerAllOfRelationshipsCampaigns"
        },
        {
            "name": "flows",
            "baseName": "flows",
            "type": "GetTagResponseCollectionDataInnerAllOfRelationshipsFlows"
        }    ];

    static getAttributeTypeMap() {
        return GetTagResponseCollectionDataInnerAllOfRelationships.attributeTypeMap;
    }
}

