/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NeverSubscribedEnum } from './neverSubscribedEnum';
export class HasEmailMarketingNeverSubscribed {
    'subscription': NeverSubscribedEnum | 'never_subscribed';
    'filters'?: any | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "NeverSubscribedEnum"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return HasEmailMarketingNeverSubscribed.attributeTypeMap;
    }
}

export namespace HasEmailMarketingNeverSubscribed {
}
