/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BlockDisplayOptions } from './blockDisplayOptions';
export class HTMLBlockData {
    'content': string;
    'displayOptions': BlockDisplayOptions;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "displayOptions",
            "baseName": "display_options",
            "type": "BlockDisplayOptions"
        }    ];

    static getAttributeTypeMap() {
        return HTMLBlockData.attributeTypeMap;
    }
}

