/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ImplicitlyOrExplicitlyReachableEnum } from './implicitlyOrExplicitlyReachableEnum';
export class ImplicitlyOrExplicitlyReachable {
    'reachableStatus': ImplicitlyOrExplicitlyReachableEnum | 'implicitly_or_explicitly_reachable';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reachableStatus",
            "baseName": "reachable_status",
            "type": "ImplicitlyOrExplicitlyReachableEnum"
        }    ];

    static getAttributeTypeMap() {
        return ImplicitlyOrExplicitlyReachable.attributeTypeMap;
    }
}

export namespace ImplicitlyOrExplicitlyReachable {
}
