/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ImplicitlyOrExplicitlyUnreachableEnum } from './implicitlyOrExplicitlyUnreachableEnum';
export class ImplicitlyOrExplicitlyUnreachable {
    'reachableStatus': ImplicitlyOrExplicitlyUnreachableEnum | 'implicitly_or_explicitly_unreachable';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reachableStatus",
            "baseName": "reachable_status",
            "type": "ImplicitlyOrExplicitlyUnreachableEnum"
        }    ];

    static getAttributeTypeMap() {
        return ImplicitlyOrExplicitlyUnreachable.attributeTypeMap;
    }
}

export namespace ImplicitlyOrExplicitlyUnreachable {
}
