/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class IpAllowlistResponse {
    /**
    * Klaviyo\'s current integration-egress IP ranges, in IPv4 CIDR notation. This is the complete, authoritative set — replace your allow list with it rather than merging.
    */
    'prefixes': Array<string>;
    /**
    * Opaque change token derived from `prefixes`. It changes only when the ranges change, so polling clients can compare it across requests to detect updates without diffing the list.
    */
    'syncToken': string;
    /**
    * When the IP range list was last changed (ISO 8601, UTC).
    */
    'created': Date;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "prefixes",
            "baseName": "prefixes",
            "type": "Array<string>"
        },
        {
            "name": "syncToken",
            "baseName": "sync_token",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return IpAllowlistResponse.attributeTypeMap;
    }
}

