/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class ListCreateQueryResourceObjectAttributes {
    /**
    * A helpful name to label the list
    */
    'name': string;
    /**
    * The opt-in process for this list. Valid values: \'double_opt_in\', \'single_opt_in\'. If not provided, uses account default.
    */
    'optInProcess'?: ListCreateQueryResourceObjectAttributes.OptInProcessEnum | 'double_opt_in' | 'single_opt_in' | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "optInProcess",
            "baseName": "opt_in_process",
            "type": "ListCreateQueryResourceObjectAttributes.OptInProcessEnum"
        }    ];

    static getAttributeTypeMap() {
        return ListCreateQueryResourceObjectAttributes.attributeTypeMap;
    }
}

export namespace ListCreateQueryResourceObjectAttributes {
    export enum OptInProcessEnum {
        DoubleOptIn = <any> 'double_opt_in',
        SingleOptIn = <any> 'single_opt_in'
    }
}
