/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LowInventoryConditionFilter2 } from './lowInventoryConditionFilter2';
import { LowInventoryPropertyEnum } from './lowInventoryPropertyEnum';
export class LowInventoryCondition {
    'type': LowInventoryPropertyEnum | 'low-inventory-property';
    'metricId': string | null;
    'field': string;
    'filter': LowInventoryConditionFilter2;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "LowInventoryPropertyEnum"
        },
        {
            "name": "metricId",
            "baseName": "metric_id",
            "type": "string"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "LowInventoryConditionFilter2"
        }    ];

    static getAttributeTypeMap() {
        return LowInventoryCondition.attributeTypeMap;
    }
}

export namespace LowInventoryCondition {
}
