/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MappedMetricEnum } from './mappedMetricEnum';
import { MappedMetricResponseObjectResourceAttributes } from './mappedMetricResponseObjectResourceAttributes';
import { ObjectLinks } from './objectLinks';
export class MappedMetricResponseObjectResource {
    'type': MappedMetricEnum | 'mapped-metric';
    /**
    * The type of mapping.
    */
    'id': MappedMetricResponseObjectResource.IdEnum | 'added_to_cart' | 'cancelled_sales' | 'ordered_product' | 'refunded_sales' | 'revenue' | 'started_checkout' | 'viewed_product';
    'attributes': MappedMetricResponseObjectResourceAttributes;
    'links': ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "MappedMetricEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "MappedMetricResponseObjectResource.IdEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "MappedMetricResponseObjectResourceAttributes"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return MappedMetricResponseObjectResource.attributeTypeMap;
    }
}

export namespace MappedMetricResponseObjectResource {
    export enum IdEnum {
        AddedToCart = <any> 'added_to_cart',
        CancelledSales = <any> 'cancelled_sales',
        OrderedProduct = <any> 'ordered_product',
        RefundedSales = <any> 'refunded_sales',
        Revenue = <any> 'revenue',
        StartedCheckout = <any> 'started_checkout',
        ViewedProduct = <any> 'viewed_product'
    }
}
