/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class MobilePushMessageContent {
    'title': string;
    'body': string;
    'sound'?: boolean = false;
    'badge'?: boolean = false;
    'mediaUrl'?: string | null;
    'dynamicImage'?: string | null;
    'iosLink'?: string | null;
    'androidLink'?: string | null;
    'onOpen'?: string = 'home';


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "sound",
            "baseName": "sound",
            "type": "boolean"
        },
        {
            "name": "badge",
            "baseName": "badge",
            "type": "boolean"
        },
        {
            "name": "mediaUrl",
            "baseName": "media_url",
            "type": "string"
        },
        {
            "name": "dynamicImage",
            "baseName": "dynamic_image",
            "type": "string"
        },
        {
            "name": "iosLink",
            "baseName": "ios_link",
            "type": "string"
        },
        {
            "name": "androidLink",
            "baseName": "android_link",
            "type": "string"
        },
        {
            "name": "onOpen",
            "baseName": "on_open",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MobilePushMessageContent.attributeTypeMap;
    }
}

