/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class MobilePushNoBadge {
    /**
    * Whether to display a badge on the app icon
    */
    'display': MobilePushNoBadge.DisplayEnum | false;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "display",
            "baseName": "display",
            "type": "MobilePushNoBadge.DisplayEnum"
        }    ];

    static getAttributeTypeMap() {
        return MobilePushNoBadge.attributeTypeMap;
    }
}

export namespace MobilePushNoBadge {
    export enum DisplayEnum {
        False = <any> false
    }
}
