/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class NonLocalStaticSend {
    /**
    * Whether the campaign should be sent with local recipient timezone send (requires UTC time) or statically sent at the given time.
    */
    'isLocal': NonLocalStaticSend.IsLocalEnum | false;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isLocal",
            "baseName": "is_local",
            "type": "NonLocalStaticSend.IsLocalEnum"
        }    ];

    static getAttributeTypeMap() {
        return NonLocalStaticSend.attributeTypeMap;
    }
}

export namespace NonLocalStaticSend {
    export enum IsLocalEnum {
        False = <any> false
    }
}
