/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectTypeCreateQueryResourceObjectAttributes } from './objectTypeCreateQueryResourceObjectAttributes';
import { ObjectTypeEnum } from './objectTypeEnum';
export class ObjectTypeCreateQueryResourceObject {
    'type': ObjectTypeEnum | 'object-type';
    'attributes': ObjectTypeCreateQueryResourceObjectAttributes;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ObjectTypeEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "ObjectTypeCreateQueryResourceObjectAttributes"
        }    ];

    static getAttributeTypeMap() {
        return ObjectTypeCreateQueryResourceObject.attributeTypeMap;
    }
}

export namespace ObjectTypeCreateQueryResourceObject {
}
