/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APISchemaProperty } from './aPISchemaProperty';
export class ObjectSchemaPartialUpdateQueryResourceObjectAttributes {
    /**
    * The title for this object schema
    */
    'title'?: string | null;
    /**
    * Properties of the object schema
    */
    'properties'?: Array<APISchemaProperty> | null;
    /**
    * The description of this object schema
    */
    'description'?: string | null;
    /**
    * The status to move this object schema to. Only `active` and `draft` may be written; setting `active` activates the schema. While activation is in progress, reads may report a `publishing` status.
    */
    'status'?: ObjectSchemaPartialUpdateQueryResourceObjectAttributes.StatusEnum | 'active' | 'draft' | null;
    /**
    * Properties that are required on the object schema
    */
    'required'?: Array<string> | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<APISchemaProperty>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ObjectSchemaPartialUpdateQueryResourceObjectAttributes.StatusEnum"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ObjectSchemaPartialUpdateQueryResourceObjectAttributes.attributeTypeMap;
    }
}

export namespace ObjectSchemaPartialUpdateQueryResourceObjectAttributes {
    export enum StatusEnum {
        Active = <any> 'active',
        Draft = <any> 'draft'
    }
}
