/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OnsiteSubscriptionCreateQueryDeprecatedOct24ResourceObjectAttributesProfile } from './onsiteSubscriptionCreateQueryDeprecatedOct24ResourceObjectAttributesProfile';
export class OnsiteSubscriptionCreateQueryDeprecatedOct24ResourceObjectAttributes {
    /**
    * A custom method detail or source to store on the consent records for this subscription.
    */
    'customSource'?: string | null;
    'profile': OnsiteSubscriptionCreateQueryDeprecatedOct24ResourceObjectAttributesProfile;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "customSource",
            "baseName": "custom_source",
            "type": "string"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "OnsiteSubscriptionCreateQueryDeprecatedOct24ResourceObjectAttributesProfile"
        }    ];

    static getAttributeTypeMap() {
        return OnsiteSubscriptionCreateQueryDeprecatedOct24ResourceObjectAttributes.attributeTypeMap;
    }
}

