/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetReviewResponseDTOCollectionCompoundDocumentDataInnerAllOfRelationshipsEvents } from './getReviewResponseDTOCollectionCompoundDocumentDataInnerAllOfRelationshipsEvents';
import { PatchReviewResponseDTODataRelationshipsItem } from './patchReviewResponseDTODataRelationshipsItem';
export class PatchReviewResponseDTODataRelationships {
    'events'?: GetReviewResponseDTOCollectionCompoundDocumentDataInnerAllOfRelationshipsEvents;
    'item'?: PatchReviewResponseDTODataRelationshipsItem;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "events",
            "baseName": "events",
            "type": "GetReviewResponseDTOCollectionCompoundDocumentDataInnerAllOfRelationshipsEvents"
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "PatchReviewResponseDTODataRelationshipsItem"
        }    ];

    static getAttributeTypeMap() {
        return PatchReviewResponseDTODataRelationships.attributeTypeMap;
    }
}

