/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SeriesData } from './seriesData';
export class PostSegmentSeriesResponseDTODataAttributes {
    /**
    * An array of all the returned values data. Each object in the array represents one unique grouping and the results for that grouping. Each value in the results array corresponds to the date time at the same index.
    */
    'results': Array<SeriesData>;
    /**
    * An array of date times which correspond to the equivalent index in the results data.
    */
    'dateTimes': Array<Date>;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<SeriesData>"
        },
        {
            "name": "dateTimes",
            "baseName": "date_times",
            "type": "Array<Date>"
        }    ];

    static getAttributeTypeMap() {
        return PostSegmentSeriesResponseDTODataAttributes.attributeTypeMap;
    }
}

