/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetTagResponseCollectionDataInnerAllOfRelationships } from './getTagResponseCollectionDataInnerAllOfRelationships';
import { ObjectLinks } from './objectLinks';
import { TagEnum } from './tagEnum';
import { TagUpdateQueryResourceObjectAttributes } from './tagUpdateQueryResourceObjectAttributes';

export class PostTagResponseData {
    'relationships'?: GetTagResponseCollectionDataInnerAllOfRelationships;
    'attributes': TagUpdateQueryResourceObjectAttributes;
    'type': TagEnum;
    /**
    * The Tag ID
    */
    'id': string;
    'links': ObjectLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GetTagResponseCollectionDataInnerAllOfRelationships"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "TagUpdateQueryResourceObjectAttributes"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TagEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return PostTagResponseData.attributeTypeMap;
    }
}

export namespace PostTagResponseData {
}
