/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PostCatalogVariantResponseDataRelationshipsItem } from './postCatalogVariantResponseDataRelationshipsItem';
export class PostCatalogVariantResponseDataRelationships {
    'item'?: PostCatalogVariantResponseDataRelationshipsItem;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "item",
            "baseName": "item",
            "type": "PostCatalogVariantResponseDataRelationshipsItem"
        }    ];

    static getAttributeTypeMap() {
        return PostCatalogVariantResponseDataRelationships.attributeTypeMap;
    }
}

