/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignSendJobEnum } from './campaignSendJobEnum';
import { ObjectLinks } from './objectLinks';
import { PostCampaignSendJobResponseDataAttributes } from './postCampaignSendJobResponseDataAttributes';

export class PostCampaignSendJobResponseData {
    'attributes': PostCampaignSendJobResponseDataAttributes;
    'type': CampaignSendJobEnum;
    /**
    * The ID of the campaign to send
    */
    'id': string;
    'links': ObjectLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "PostCampaignSendJobResponseDataAttributes"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CampaignSendJobEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return PostCampaignSendJobResponseData.attributeTypeMap;
    }
}

export namespace PostCampaignSendJobResponseData {
}
