/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PriceDropConditionFilter2 } from './priceDropConditionFilter2';
import { PriceDropPropertyEnum } from './priceDropPropertyEnum';
export class PriceDropCondition {
    'type': PriceDropPropertyEnum | 'price-drop-property';
    'metricId': string | null;
    'field': string;
    'filter': PriceDropConditionFilter2;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PriceDropPropertyEnum"
        },
        {
            "name": "metricId",
            "baseName": "metric_id",
            "type": "string"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "PriceDropConditionFilter2"
        }    ];

    static getAttributeTypeMap() {
        return PriceDropCondition.attributeTypeMap;
    }
}

export namespace PriceDropCondition {
}
