/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfileNotInFlowConditionTimeframeFilter } from './profileNotInFlowConditionTimeframeFilter';
import { ProfileNotSentPushEnum } from './profileNotSentPushEnum';
export class ProfileHasNotReceivedPushMessageCondition {
    'type': ProfileNotSentPushEnum | 'profile-not-sent-push';
    'timeframeFilter': ProfileNotInFlowConditionTimeframeFilter;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProfileNotSentPushEnum"
        },
        {
            "name": "timeframeFilter",
            "baseName": "timeframe_filter",
            "type": "ProfileNotInFlowConditionTimeframeFilter"
        }    ];

    static getAttributeTypeMap() {
        return ProfileHasNotReceivedPushMessageCondition.attributeTypeMap;
    }
}

export namespace ProfileHasNotReceivedPushMessageCondition {
}
