/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProfileIdentifierDTOResourceObjectAttributes {
    /**
    * Individual\'s email address
    */
    'email'?: string;
    /**
    * Individual\'s phone number in E.164 format
    */
    'phoneNumber'?: string;
    /**
    * A unique identifier used by customers to associate Klaviyo profiles with profiles in an external system, such as a point-of-sale system. Format varies based on the external system.
    */
    'externalId'?: string;
    'anonymousId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "anonymousId",
            "baseName": "anonymous_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProfileIdentifierDTOResourceObjectAttributes.attributeTypeMap;
    }
}

