/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscriptionChannels } from './subscriptionChannels';

export class ProfileSubscriptionCreateQueryResourceObjectAttributes {
    /**
    * The phone number to subscribe or to set on the profile if `channels` is specified and the SMS channel is omitted.
    */
    'phoneNumber'?: string;
    /**
    * The email address to subscribe or to set on the profile if `channels` is specified and the email channel is omitted.
    */
    'email'?: string;
    'subscriptions'?: SubscriptionChannels;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "subscriptions",
            "baseName": "subscriptions",
            "type": "SubscriptionChannels"
        }    ];

    static getAttributeTypeMap() {
        return ProfileSubscriptionCreateQueryResourceObjectAttributes.attributeTypeMap;
    }
}

