/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExplicitlyReachable } from './explicitlyReachable';
import { ExplicitlyReachableFiltersInner } from './explicitlyReachableFiltersInner';
import { ExplicitlyUnreachable } from './explicitlyUnreachable';
import { ImplicitlyOrExplicitlyReachable } from './implicitlyOrExplicitlyReachable';
import { ImplicitlyOrExplicitlyUnreachable } from './implicitlyOrExplicitlyUnreachable';
import { ImplicitlyOrExplicitlyUnreachableEnum } from './implicitlyOrExplicitlyUnreachableEnum';
import { ImplicitlyReachable } from './implicitlyReachable';
import { ImplicitlyUnreachable } from './implicitlyUnreachable';
export type ProfilePermissionsConditionPermission = ExplicitlyReachable | ImplicitlyReachable | ImplicitlyOrExplicitlyReachable | ExplicitlyUnreachable | ImplicitlyUnreachable | ImplicitlyOrExplicitlyUnreachable;
