/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectLinks } from './objectLinks';
import { ProfileEnum } from './profileEnum';
import { ProfileResponsePluralConversationsObjectResourceExtendedAttributes } from './profileResponsePluralConversationsObjectResourceExtendedAttributes';
import { ProfileResponsePluralConversationsObjectResourceExtendedRelationships } from './profileResponsePluralConversationsObjectResourceExtendedRelationships';
export class ProfileResponsePluralConversationsObjectResourceExtended {
    'type': ProfileEnum | 'profile';
    /**
    * Primary key that uniquely identifies this profile. Generated by Klaviyo.
    */
    'id'?: string | null;
    'attributes': ProfileResponsePluralConversationsObjectResourceExtendedAttributes;
    'relationships'?: ProfileResponsePluralConversationsObjectResourceExtendedRelationships;
    'links': ObjectLinks;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProfileEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "ProfileResponsePluralConversationsObjectResourceExtendedAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "ProfileResponsePluralConversationsObjectResourceExtendedRelationships"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ObjectLinks"
        }    ];

    static getAttributeTypeMap() {
        return ProfileResponsePluralConversationsObjectResourceExtended.attributeTypeMap;
    }
}

export namespace ProfileResponsePluralConversationsObjectResourceExtended {
}
