/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class PushOnOpenWebUrl {
    'type': PushOnOpenWebUrl.TypeEnum | 'open_web_url';
    /**
    * External url to open when push notification is triggered
    */
    'webUrl'?: string | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PushOnOpenWebUrl.TypeEnum"
        },
        {
            "name": "webUrl",
            "baseName": "web_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PushOnOpenWebUrl.attributeTypeMap;
    }
}

export namespace PushOnOpenWebUrl {
    export enum TypeEnum {
        OpenWebUrl = <any> 'open_web_url'
    }
}
