/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PushProfileUpsertQueryResourceObject } from './pushProfileUpsertQueryResourceObject';
/**
* The profile associated with the push token to create/update
*/
export class PushTokenCreateQueryResourceObjectAttributesProfile {
    'data': PushProfileUpsertQueryResourceObject;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "PushProfileUpsertQueryResourceObject"
        }    ];

    static getAttributeTypeMap() {
        return PushTokenCreateQueryResourceObjectAttributesProfile.attributeTypeMap;
    }
}

