/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
export class QuoteStyle {
    'fontFamily'?: string = 'Arial, \'Helvetica Neue\', Helvetica, sans-serif';
    'fontSize'?: number = 16;
    'textColor'?: string = '#000000';
    'characterSpacing'?: number = 0;
    'fontWeight'?: number = 400;
    /**
    * Horizontal alignment enumeration.
    */
    'alignment'?: QuoteStyle.AlignmentEnum | 'center' | 'left' | 'right' = QuoteStyle.AlignmentEnum.Center;
    'lineHeight'?: number = 1.5;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fontFamily",
            "baseName": "font_family",
            "type": "string"
        },
        {
            "name": "fontSize",
            "baseName": "font_size",
            "type": "number"
        },
        {
            "name": "textColor",
            "baseName": "text_color",
            "type": "string"
        },
        {
            "name": "characterSpacing",
            "baseName": "character_spacing",
            "type": "number"
        },
        {
            "name": "fontWeight",
            "baseName": "font_weight",
            "type": "number"
        },
        {
            "name": "alignment",
            "baseName": "alignment",
            "type": "QuoteStyle.AlignmentEnum"
        },
        {
            "name": "lineHeight",
            "baseName": "line_height",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return QuoteStyle.attributeTypeMap;
    }
}

export namespace QuoteStyle {
    export enum AlignmentEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
}
