/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Padding } from './padding';
export class RadioButtonsStyles {
    'padding'?: Padding;
    'backgroundColor'?: string | null;
    /**
    * Arrangement enumeration.
    */
    'arrangement'?: RadioButtonsStyles.ArrangementEnum | 'horizontal' | 'vertical' = RadioButtonsStyles.ArrangementEnum.Vertical;
    /**
    * Horizontal alignment enumeration.
    */
    'alignment'?: RadioButtonsStyles.AlignmentEnum | 'center' | 'left' | 'right' = RadioButtonsStyles.AlignmentEnum.Left;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "padding",
            "baseName": "padding",
            "type": "Padding"
        },
        {
            "name": "backgroundColor",
            "baseName": "background_color",
            "type": "string"
        },
        {
            "name": "arrangement",
            "baseName": "arrangement",
            "type": "RadioButtonsStyles.ArrangementEnum"
        },
        {
            "name": "alignment",
            "baseName": "alignment",
            "type": "RadioButtonsStyles.AlignmentEnum"
        }    ];

    static getAttributeTypeMap() {
        return RadioButtonsStyles.attributeTypeMap;
    }
}

export namespace RadioButtonsStyles {
    export enum ArrangementEnum {
        Horizontal = <any> 'horizontal',
        Vertical = <any> 'vertical'
    }
    export enum AlignmentEnum {
        Center = <any> 'center',
        Left = <any> 'left',
        Right = <any> 'right'
    }
}
