/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { STOScheduleOptions } from './sTOScheduleOptions';
import { StaticScheduleOptions } from './staticScheduleOptions';
import { ThrottledScheduleOptions } from './throttledScheduleOptions';

export class SendStrategySubObject {
    'optionsSto'?: STOScheduleOptions;
    /**
    * Describes the shape of the options object. Allowed values: [\'static\', \'throttled\', \'immediate\', \'smart_send_time\']
    */
    'method': string;
    'optionsThrottled'?: ThrottledScheduleOptions;
    'optionsStatic'?: StaticScheduleOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "optionsSto",
            "baseName": "options_sto",
            "type": "STOScheduleOptions"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string"
        },
        {
            "name": "optionsThrottled",
            "baseName": "options_throttled",
            "type": "ThrottledScheduleOptions"
        },
        {
            "name": "optionsStatic",
            "baseName": "options_static",
            "type": "StaticScheduleOptions"
        }    ];

    static getAttributeTypeMap() {
        return SendStrategySubObject.attributeTypeMap;
    }
}

