/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SMSDisclosureProperties } from './sMSDisclosureProperties';
import { SMSDisclosureStyles } from './sMSDisclosureStyles';
import { SmsDisclosureEnum } from './smsDisclosureEnum';
export class SMSDisclosure {
    'id'?: string | null;
    'type': SmsDisclosureEnum | 'sms_disclosure';
    'styles'?: SMSDisclosureStyles;
    'properties'?: SMSDisclosureProperties;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SmsDisclosureEnum"
        },
        {
            "name": "styles",
            "baseName": "styles",
            "type": "SMSDisclosureStyles"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "SMSDisclosureProperties"
        }    ];

    static getAttributeTypeMap() {
        return SMSDisclosure.attributeTypeMap;
    }
}

export namespace SMSDisclosure {
}
