/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SMSMarketing {
    /**
    * Whether or not this profile is subscribed to receive SMS marketing.
    */
    'canReceiveSmsMarketing': boolean;
    /**
    * The consent status for SMS marketing.
    */
    'consent': string;
    /**
    * The timestamp when consent was recorded or updated for SMS marketing, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm).
    */
    'consentTimestamp': Date;
    /**
    * The method by which the profile was subscribed to SMS marketing.
    */
    'method': string;
    /**
    * Additional details about the method which the profile was subscribed to SMS marketing. This may be empty if no details were provided.
    */
    'methodDetail'?: string = '';
    /**
    * The timestamp when the SMS consent record was last modified, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm).
    */
    'lastUpdated': Date;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "canReceiveSmsMarketing",
            "baseName": "can_receive_sms_marketing",
            "type": "boolean"
        },
        {
            "name": "consent",
            "baseName": "consent",
            "type": "string"
        },
        {
            "name": "consentTimestamp",
            "baseName": "consent_timestamp",
            "type": "Date"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string"
        },
        {
            "name": "methodDetail",
            "baseName": "method_detail",
            "type": "string"
        },
        {
            "name": "lastUpdated",
            "baseName": "last_updated",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return SMSMarketing.attributeTypeMap;
    }
}

