/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UTMParamsSubObject } from './uTMParamsSubObject';

export class SMSTrackingOptionsSubObject {
    /**
    * A list of UTM parameters. If an empty list is given and is_add_utm is True, uses company defaults.
    */
    'utmParams'?: Array<UTMParamsSubObject>;
    /**
    * Whether the campaign needs UTM parameters. If set to False, UTM params will not be used.
    */
    'isAddUtm'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "utmParams",
            "baseName": "utm_params",
            "type": "Array<UTMParamsSubObject>"
        },
        {
            "name": "isAddUtm",
            "baseName": "is_add_utm",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SMSTrackingOptionsSubObject.attributeTypeMap;
    }
}

