/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfileSubscriptionBulkDeleteJobEnum } from './profileSubscriptionBulkDeleteJobEnum';
import { SubscriptionDeleteJobCreateQueryResourceObjectAttributes } from './subscriptionDeleteJobCreateQueryResourceObjectAttributes';
import { SubscriptionDeleteJobCreateQueryResourceObjectRelationships } from './subscriptionDeleteJobCreateQueryResourceObjectRelationships';

export class SubscriptionDeleteJobCreateQueryResourceObject {
    'type': ProfileSubscriptionBulkDeleteJobEnum | 'profile-subscription-bulk-delete-job';
    'attributes': SubscriptionDeleteJobCreateQueryResourceObjectAttributes;
    'relationships'?: SubscriptionDeleteJobCreateQueryResourceObjectRelationships;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProfileSubscriptionBulkDeleteJobEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "SubscriptionDeleteJobCreateQueryResourceObjectAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "SubscriptionDeleteJobCreateQueryResourceObjectRelationships"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionDeleteJobCreateQueryResourceObject.attributeTypeMap;
    }
}

export namespace SubscriptionDeleteJobCreateQueryResourceObject {
}
