/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscriptionCreateJobCreateQueryResourceObjectAttributesProfiles } from './subscriptionCreateJobCreateQueryResourceObjectAttributesProfiles';

export class SubscriptionCreateJobCreateQueryResourceObjectAttributes {
    'profiles': SubscriptionCreateJobCreateQueryResourceObjectAttributesProfiles;
    /**
    * A custom method detail or source to store on the consent records.
    */
    'customSource'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "profiles",
            "baseName": "profiles",
            "type": "SubscriptionCreateJobCreateQueryResourceObjectAttributesProfiles"
        },
        {
            "name": "customSource",
            "baseName": "custom_source",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionCreateJobCreateQueryResourceObjectAttributes.attributeTypeMap;
    }
}

