/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomTrackingParamDTO } from './customTrackingParamDTO';
import { TrackingParamDTO } from './trackingParamDTO';
export class TrackingSettingResponseObjectResourceAttributes {
    /**
    * Whether tracking parameters are automatically added to campaigns and flows.
    */
    'autoAddParameters': boolean;
    'utmSource': TrackingParamDTO;
    'utmMedium': TrackingParamDTO;
    'utmCampaign'?: TrackingParamDTO;
    'utmId'?: TrackingParamDTO;
    'utmTerm'?: TrackingParamDTO;
    /**
    * Additional custom tracking parameters.
    */
    'customParameters'?: Array<CustomTrackingParamDTO> | null;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "autoAddParameters",
            "baseName": "auto_add_parameters",
            "type": "boolean"
        },
        {
            "name": "utmSource",
            "baseName": "utm_source",
            "type": "TrackingParamDTO"
        },
        {
            "name": "utmMedium",
            "baseName": "utm_medium",
            "type": "TrackingParamDTO"
        },
        {
            "name": "utmCampaign",
            "baseName": "utm_campaign",
            "type": "TrackingParamDTO"
        },
        {
            "name": "utmId",
            "baseName": "utm_id",
            "type": "TrackingParamDTO"
        },
        {
            "name": "utmTerm",
            "baseName": "utm_term",
            "type": "TrackingParamDTO"
        },
        {
            "name": "customParameters",
            "baseName": "custom_parameters",
            "type": "Array<CustomTrackingParamDTO>"
        }    ];

    static getAttributeTypeMap() {
        return TrackingSettingResponseObjectResourceAttributes.attributeTypeMap;
    }
}

