/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NumericEnum } from './numericEnum';
import { UnionPositiveNumericFilterOperator } from './unionPositiveNumericFilterOperator';
export class UnionPositiveNumericFilter {
    'type': NumericEnum | 'numeric';
    'operator': UnionPositiveNumericFilterOperator;
    'value': number;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "NumericEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "UnionPositiveNumericFilterOperator"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UnionPositiveNumericFilter.attributeTypeMap;
    }
}

export namespace UnionPositiveNumericFilter {
}
