/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UniqueEnum } from './uniqueEnum';
export class UniqueCouponConfig {
    'type': UniqueEnum | 'unique';
    'id'?: number | null;
    'code'?: string | null;
    'fallbackCouponCode'?: string | null;
    /**
    * Timeframes for the signup counter lookback.
    */
    'integration'?: UniqueCouponConfig.IntegrationEnum | 'shopify' | 'uploaded' = UniqueCouponConfig.IntegrationEnum.Shopify;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "UniqueEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "fallbackCouponCode",
            "baseName": "fallback_coupon_code",
            "type": "string"
        },
        {
            "name": "integration",
            "baseName": "integration",
            "type": "UniqueCouponConfig.IntegrationEnum"
        }    ];

    static getAttributeTypeMap() {
        return UniqueCouponConfig.attributeTypeMap;
    }
}

export namespace UniqueCouponConfig {
    export enum IntegrationEnum {
        Shopify = <any> 'shopify',
        Uploaded = <any> 'uploaded'
    }
}
