/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TemplateUniversalContentEnum } from './templateUniversalContentEnum';
import { UniversalContentPartialUpdateQueryResourceObjectAttributes } from './universalContentPartialUpdateQueryResourceObjectAttributes';
export class UniversalContentPartialUpdateQueryResourceObject {
    'type': TemplateUniversalContentEnum | 'template-universal-content';
    /**
    * The ID of the template universal content
    */
    'id': string;
    'attributes': UniversalContentPartialUpdateQueryResourceObjectAttributes;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TemplateUniversalContentEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "UniversalContentPartialUpdateQueryResourceObjectAttributes"
        }    ];

    static getAttributeTypeMap() {
        return UniversalContentPartialUpdateQueryResourceObject.attributeTypeMap;
    }
}

export namespace UniversalContentPartialUpdateQueryResourceObject {
}
