/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ButtonBlockV0 } from './buttonBlockV0';
import { CouponBlockV0 } from './couponBlockV0';
import { DropShadowBlockV0 } from './dropShadowBlockV0';
import { HTMLBlockV0 } from './hTMLBlockV0';
import { HeaderBlockV0 } from './headerBlockV0';
import { HorizontalRuleBlockV0 } from './horizontalRuleBlockV0';
import { ImageBlockV0 } from './imageBlockV0';
import { ProductBlockV0 } from './productBlockV0';
import { ReviewBlockV0 } from './reviewBlockV0';
import { SectionV0 } from './sectionV0';
import { SocialBlockV0 } from './socialBlockV0';
import { SpacerBlockV0 } from './spacerBlockV0';
import { SplitBlockV0 } from './splitBlockV0';
import { TableBlockV0 } from './tableBlockV0';
import { TextBlockV0 } from './textBlockV0';
import { UnsupportedBlock } from './unsupportedBlock';
import { VideoBlockV0 } from './videoBlockV0';
export type UniversalContentResponseObjectResourceAttributesDefinition = ButtonBlockV0 | CouponBlockV0 | DropShadowBlockV0 | HeaderBlockV0 | HorizontalRuleBlockV0 | HTMLBlockV0 | ImageBlockV0 | ProductBlockV0 | ReviewBlockV0 | SocialBlockV0 | SpacerBlockV0 | SplitBlockV0 | TableBlockV0 | TextBlockV0 | UnsupportedBlock | VideoBlockV0 | SectionV0;
