/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfileUnsubscriptionBulkCreateJobEnum } from './profileUnsubscriptionBulkCreateJobEnum';
import { UnsubscriptionCreateJobCreateQueryDeprecatedResourceObjectAttributes } from './unsubscriptionCreateJobCreateQueryDeprecatedResourceObjectAttributes';
export class UnsubscriptionCreateJobCreateQueryDeprecatedResourceObject {
    'type': ProfileUnsubscriptionBulkCreateJobEnum | 'profile-unsubscription-bulk-create-job';
    'attributes': UnsubscriptionCreateJobCreateQueryDeprecatedResourceObjectAttributes;


    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProfileUnsubscriptionBulkCreateJobEnum"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "UnsubscriptionCreateJobCreateQueryDeprecatedResourceObjectAttributes"
        }    ];

    static getAttributeTypeMap() {
        return UnsubscriptionCreateJobCreateQueryDeprecatedResourceObject.attributeTypeMap;
    }
}

export namespace UnsubscriptionCreateJobCreateQueryDeprecatedResourceObject {
}
