/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-08-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {CampaignMessageAssignTemplateQueryResourceObjectRelationshipsTemplate} from './CampaignMessageAssignTemplateQueryResourceObjectRelationshipsTemplate.js';

/**
 * The CampaignMessageAssignTemplateQueryResourceObjectRelationships model module.
 * @module model/CampaignMessageAssignTemplateQueryResourceObjectRelationships
 * @version 2023-08-15
 */
export class CampaignMessageAssignTemplateQueryResourceObjectRelationships {
  /**
   * Constructs a new <code>CampaignMessageAssignTemplateQueryResourceObjectRelationships</code>.
   * @alias module:model/CampaignMessageAssignTemplateQueryResourceObjectRelationships
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CampaignMessageAssignTemplateQueryResourceObjectRelationships</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CampaignMessageAssignTemplateQueryResourceObjectRelationships} obj Optional instance to populate.
   * @return {module:model/CampaignMessageAssignTemplateQueryResourceObjectRelationships} The populated <code>CampaignMessageAssignTemplateQueryResourceObjectRelationships</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CampaignMessageAssignTemplateQueryResourceObjectRelationships();
      if (data.hasOwnProperty('template'))
        obj.template = CampaignMessageAssignTemplateQueryResourceObjectRelationshipsTemplate.constructFromObject(data['template']);
    }
    return obj;
  }
}

/**
 * @member {module:model/CampaignMessageAssignTemplateQueryResourceObjectRelationshipsTemplate} template
 */
CampaignMessageAssignTemplateQueryResourceObjectRelationships.prototype.template = undefined;

