/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-02-22
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {CampaignCloneQueryAsSubResourceAttributes} from './CampaignCloneQueryAsSubResourceAttributes.js';

/**
 * The CampaignCloneQueryAsSubResource model module.
 * @module model/CampaignCloneQueryAsSubResource
 * @version 2023-02-22
 */
export class CampaignCloneQueryAsSubResource {
  /**
   * Constructs a new <code>CampaignCloneQueryAsSubResource</code>.
   * @alias module:model/CampaignCloneQueryAsSubResource
   * @class
   * @param type {module:model/CampaignCloneQueryAsSubResource.TypeEnum} 
   * @param attributes {module:model/CampaignCloneQueryAsSubResourceAttributes} 
   */
  constructor(type, attributes) {
    this.type = type;
    this.attributes = attributes;
  }

  /**
   * Constructs a <code>CampaignCloneQueryAsSubResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CampaignCloneQueryAsSubResource} obj Optional instance to populate.
   * @return {module:model/CampaignCloneQueryAsSubResource} The populated <code>CampaignCloneQueryAsSubResource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CampaignCloneQueryAsSubResource();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('attributes'))
        obj.attributes = CampaignCloneQueryAsSubResourceAttributes.constructFromObject(data['attributes']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CampaignCloneQueryAsSubResource.TypeEnum = {
  /**
   * value: "campaign"
   * @const
   */
  campaign: "campaign"
};
/**
 * @member {module:model/CampaignCloneQueryAsSubResource.TypeEnum} type
 */
CampaignCloneQueryAsSubResource.prototype.type = undefined;

/**
 * @member {module:model/CampaignCloneQueryAsSubResourceAttributes} attributes
 */
CampaignCloneQueryAsSubResource.prototype.attributes = undefined;

