/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {CatalogItemBulkDeleteJobEnum} from './CatalogItemBulkDeleteJobEnum.js';
import {CatalogItemDeleteJobCreateQueryResourceObjectAttributes} from './CatalogItemDeleteJobCreateQueryResourceObjectAttributes.js';

/**
 * The CatalogItemDeleteJobCreateQueryResourceObject model module.
 * @module model/CatalogItemDeleteJobCreateQueryResourceObject
 * @version 2023-07-15
 */
export class CatalogItemDeleteJobCreateQueryResourceObject {
  /**
   * Constructs a new <code>CatalogItemDeleteJobCreateQueryResourceObject</code>.
   * @alias module:model/CatalogItemDeleteJobCreateQueryResourceObject
   * @class
   * @param attributes {module:model/CatalogItemDeleteJobCreateQueryResourceObjectAttributes} 
   * @param type {module:model/CatalogItemBulkDeleteJobEnum} 
   */
  constructor(attributes, type) {
    this.attributes = attributes;
    this.type = type;
  }

  /**
   * Constructs a <code>CatalogItemDeleteJobCreateQueryResourceObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogItemDeleteJobCreateQueryResourceObject} obj Optional instance to populate.
   * @return {module:model/CatalogItemDeleteJobCreateQueryResourceObject} The populated <code>CatalogItemDeleteJobCreateQueryResourceObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CatalogItemDeleteJobCreateQueryResourceObject();
      if (data.hasOwnProperty('attributes'))
        obj.attributes = CatalogItemDeleteJobCreateQueryResourceObjectAttributes.constructFromObject(data['attributes']);
      if (data.hasOwnProperty('type'))
        obj.type = CatalogItemBulkDeleteJobEnum.constructFromObject(data['type']);
    }
    return obj;
  }
}

/**
 * @member {module:model/CatalogItemDeleteJobCreateQueryResourceObjectAttributes} attributes
 */
CatalogItemDeleteJobCreateQueryResourceObject.prototype.attributes = undefined;

/**
 * @member {module:model/CatalogItemBulkDeleteJobEnum} type
 */
CatalogItemDeleteJobCreateQueryResourceObject.prototype.type = undefined;

