/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {CatalogVariantDeleteQueryResourceObject} from './CatalogVariantDeleteQueryResourceObject.js';

/**
 * The CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants model module.
 * @module model/CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants
 * @version 2023-07-15
 */
export class CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants {
  /**
   * Constructs a new <code>CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants</code>.
   * Array of catalog variants to delete.
   * @alias module:model/CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants
   * @class
   * @param data {Array.<module:model/CatalogVariantDeleteQueryResourceObject>} 
   */
  constructor(data) {
    this.data = data;
  }

  /**
   * Constructs a <code>CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants} obj Optional instance to populate.
   * @return {module:model/CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants} The populated <code>CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [CatalogVariantDeleteQueryResourceObject]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/CatalogVariantDeleteQueryResourceObject>} data
 */
CatalogVariantDeleteJobCreateQueryResourceObjectAttributesVariants.prototype.data = undefined;

