/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {CatalogCategoryUpdateJobCreateQueryAsSubResourceAttributes} from './CatalogCategoryUpdateJobCreateQueryAsSubResourceAttributes.js';

/**
 * The CatalogCategoryUpdateJobCreateQueryAsSubResource model module.
 * @module model/CatalogCategoryUpdateJobCreateQueryAsSubResource
 * @version 2022-10-17
 */
export class CatalogCategoryUpdateJobCreateQueryAsSubResource {
  /**
   * Constructs a new <code>CatalogCategoryUpdateJobCreateQueryAsSubResource</code>.
   * @alias module:model/CatalogCategoryUpdateJobCreateQueryAsSubResource
   * @class
   * @param type {module:model/CatalogCategoryUpdateJobCreateQueryAsSubResource.TypeEnum} 
   * @param attributes {module:model/CatalogCategoryUpdateJobCreateQueryAsSubResourceAttributes} 
   */
  constructor(type, attributes) {
    this.type = type;
    this.attributes = attributes;
  }

  /**
   * Constructs a <code>CatalogCategoryUpdateJobCreateQueryAsSubResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogCategoryUpdateJobCreateQueryAsSubResource} obj Optional instance to populate.
   * @return {module:model/CatalogCategoryUpdateJobCreateQueryAsSubResource} The populated <code>CatalogCategoryUpdateJobCreateQueryAsSubResource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CatalogCategoryUpdateJobCreateQueryAsSubResource();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('attributes'))
        obj.attributes = CatalogCategoryUpdateJobCreateQueryAsSubResourceAttributes.constructFromObject(data['attributes']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CatalogCategoryUpdateJobCreateQueryAsSubResource.TypeEnum = {
  /**
   * value: "catalog-category-bulk-update-job"
   * @const
   */
  catalogCategoryBulkUpdateJob: "catalog-category-bulk-update-job"
};
/**
 * @member {module:model/CatalogCategoryUpdateJobCreateQueryAsSubResource.TypeEnum} type
 */
CatalogCategoryUpdateJobCreateQueryAsSubResource.prototype.type = undefined;

/**
 * @member {module:model/CatalogCategoryUpdateJobCreateQueryAsSubResourceAttributes} attributes
 */
CatalogCategoryUpdateJobCreateQueryAsSubResource.prototype.attributes = undefined;

