/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-08-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {CatalogVariantCreateQueryResourceObjectRelationshipsItemData} from './CatalogVariantCreateQueryResourceObjectRelationshipsItemData.js';

/**
 * The CatalogCategoryCreateQueryResourceObjectRelationshipsItems model module.
 * @module model/CatalogCategoryCreateQueryResourceObjectRelationshipsItems
 * @version 2023-08-15
 */
export class CatalogCategoryCreateQueryResourceObjectRelationshipsItems {
  /**
   * Constructs a new <code>CatalogCategoryCreateQueryResourceObjectRelationshipsItems</code>.
   * @alias module:model/CatalogCategoryCreateQueryResourceObjectRelationshipsItems
   * @class
   * @param data {Array.<module:model/CatalogVariantCreateQueryResourceObjectRelationshipsItemData>} 
   */
  constructor(data) {
    this.data = data;
  }

  /**
   * Constructs a <code>CatalogCategoryCreateQueryResourceObjectRelationshipsItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogCategoryCreateQueryResourceObjectRelationshipsItems} obj Optional instance to populate.
   * @return {module:model/CatalogCategoryCreateQueryResourceObjectRelationshipsItems} The populated <code>CatalogCategoryCreateQueryResourceObjectRelationshipsItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CatalogCategoryCreateQueryResourceObjectRelationshipsItems();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [CatalogVariantCreateQueryResourceObjectRelationshipsItemData]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/CatalogVariantCreateQueryResourceObjectRelationshipsItemData>} data
 */
CatalogCategoryCreateQueryResourceObjectRelationshipsItems.prototype.data = undefined;

