/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-02-22
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {CatalogVariantCreateQueryResourceObjectRelationshipsItemsData} from './CatalogVariantCreateQueryResourceObjectRelationshipsItemsData.js';

/**
 * The CatalogVariantCreateQueryResourceObjectRelationshipsItems model module.
 * @module model/CatalogVariantCreateQueryResourceObjectRelationshipsItems
 * @version 2023-02-22
 */
export class CatalogVariantCreateQueryResourceObjectRelationshipsItems {
  /**
   * Constructs a new <code>CatalogVariantCreateQueryResourceObjectRelationshipsItems</code>.
   * @alias module:model/CatalogVariantCreateQueryResourceObjectRelationshipsItems
   * @class
   * @param data {Array.<module:model/CatalogVariantCreateQueryResourceObjectRelationshipsItemsData>} 
   */
  constructor(data) {
    this.data = data;
  }

  /**
   * Constructs a <code>CatalogVariantCreateQueryResourceObjectRelationshipsItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogVariantCreateQueryResourceObjectRelationshipsItems} obj Optional instance to populate.
   * @return {module:model/CatalogVariantCreateQueryResourceObjectRelationshipsItems} The populated <code>CatalogVariantCreateQueryResourceObjectRelationshipsItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CatalogVariantCreateQueryResourceObjectRelationshipsItems();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [CatalogVariantCreateQueryResourceObjectRelationshipsItemsData]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/CatalogVariantCreateQueryResourceObjectRelationshipsItemsData>} data
 */
CatalogVariantCreateQueryResourceObjectRelationshipsItems.prototype.data = undefined;

