/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {DataPrivacyProfileQueryResourceObject} from './DataPrivacyProfileQueryResourceObject.js';

/**
 * The DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile model module.
 * @module model/DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile
 * @version 2023-07-15
 */
export class DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile {
  /**
   * Constructs a new <code>DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile</code>.
   * @alias module:model/DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile
   * @class
   * @param data {module:model/DataPrivacyProfileQueryResourceObject} 
   */
  constructor(data) {
    this.data = data;
  }

  /**
   * Constructs a <code>DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile} obj Optional instance to populate.
   * @return {module:model/DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile} The populated <code>DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile();
      if (data.hasOwnProperty('data'))
        obj.data = DataPrivacyProfileQueryResourceObject.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:model/DataPrivacyProfileQueryResourceObject} data
 */
DataPrivacyCreateDeletionJobQueryResourceObjectAttributesProfile.prototype.data = undefined;

