/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-02-22
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The EmailMarketingSuppression model module.
 * @module model/EmailMarketingSuppression
 * @version 2023-02-22
 */
export class EmailMarketingSuppression {
  /**
   * Constructs a new <code>EmailMarketingSuppression</code>.
   * @alias module:model/EmailMarketingSuppression
   * @class
   * @param reason {String} The reason the profile was suppressed from the list.
   * @param timestamp {Date} The timestamp when the profile was suppressed from the list, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm).
   */
  constructor(reason, timestamp) {
    this.reason = reason;
    this.timestamp = timestamp;
  }

  /**
   * Constructs a <code>EmailMarketingSuppression</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmailMarketingSuppression} obj Optional instance to populate.
   * @return {module:model/EmailMarketingSuppression} The populated <code>EmailMarketingSuppression</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EmailMarketingSuppression();
      if (data.hasOwnProperty('reason'))
        obj.reason = ApiClient.convertToType(data['reason'], 'String');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Date');
    }
    return obj;
  }
}

/**
 * The reason the profile was suppressed from the list.
 * @member {String} reason
 */
EmailMarketingSuppression.prototype.reason = undefined;

/**
 * The timestamp when the profile was suppressed from the list, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm).
 * @member {Date} timestamp
 */
EmailMarketingSuppression.prototype.timestamp = undefined;

