/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-02-22
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The IncludedListsAttributes model module.
 * @module model/IncludedListsAttributes
 * @version 2023-02-22
 */
export class IncludedListsAttributes {
  /**
   * Constructs a new <code>IncludedListsAttributes</code>.
   * @alias module:model/IncludedListsAttributes
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IncludedListsAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IncludedListsAttributes} obj Optional instance to populate.
   * @return {module:model/IncludedListsAttributes} The populated <code>IncludedListsAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IncludedListsAttributes();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
    }
    return obj;
  }
}

/**
 * A helpful name to label the list
 * @member {String} name
 */
IncludedListsAttributes.prototype.name = undefined;

/**
 * Date and time when the list was created, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)
 * @member {Date} created
 */
IncludedListsAttributes.prototype.created = undefined;

/**
 * Date and time when the list was last updated, in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)
 * @member {Date} updated
 */
IncludedListsAttributes.prototype.updated = undefined;

