/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-07-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {ProfileMetaPatchProperties} from './ProfileMetaPatchProperties.js';

/**
 * The OnsiteProfileMeta model module.
 * @module model/OnsiteProfileMeta
 * @version 2023-07-15
 */
export class OnsiteProfileMeta {
  /**
   * Constructs a new <code>OnsiteProfileMeta</code>.
   * @alias module:model/OnsiteProfileMeta
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OnsiteProfileMeta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OnsiteProfileMeta} obj Optional instance to populate.
   * @return {module:model/OnsiteProfileMeta} The populated <code>OnsiteProfileMeta</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OnsiteProfileMeta();
      if (data.hasOwnProperty('patch_properties'))
        obj.patchProperties = ProfileMetaPatchProperties.constructFromObject(data['patch_properties']);
    }
    return obj;
  }
}

/**
 * @member {module:model/ProfileMetaPatchProperties} patchProperties
 */
OnsiteProfileMeta.prototype.patchProperties = undefined;

