/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-02-22
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The OnsiteSubscriptionCreateQueryResourceObjectAttributes model module.
 * @module model/OnsiteSubscriptionCreateQueryResourceObjectAttributes
 * @version 2023-02-22
 */
export class OnsiteSubscriptionCreateQueryResourceObjectAttributes {
  /**
   * Constructs a new <code>OnsiteSubscriptionCreateQueryResourceObjectAttributes</code>.
   * @alias module:model/OnsiteSubscriptionCreateQueryResourceObjectAttributes
   * @class
   * @param listId {String} The list ID to add the newly subscribed profile to.
   */
  constructor(listId) {
    this.listId = listId;
  }

  /**
   * Constructs a <code>OnsiteSubscriptionCreateQueryResourceObjectAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OnsiteSubscriptionCreateQueryResourceObjectAttributes} obj Optional instance to populate.
   * @return {module:model/OnsiteSubscriptionCreateQueryResourceObjectAttributes} The populated <code>OnsiteSubscriptionCreateQueryResourceObjectAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OnsiteSubscriptionCreateQueryResourceObjectAttributes();
      if (data.hasOwnProperty('list_id'))
        obj.listId = ApiClient.convertToType(data['list_id'], 'String');
      if (data.hasOwnProperty('custom_source'))
        obj.customSource = ApiClient.convertToType(data['custom_source'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phone_number'))
        obj.phoneNumber = ApiClient.convertToType(data['phone_number'], 'String');
      if (data.hasOwnProperty('properties'))
        obj.properties = ApiClient.convertToType(data['properties'], Object);
    }
    return obj;
  }
}

/**
 * The list ID to add the newly subscribed profile to.
 * @member {String} listId
 */
OnsiteSubscriptionCreateQueryResourceObjectAttributes.prototype.listId = undefined;

/**
 * A custom method detail or source to store on the consent records for this subscription.
 * @member {String} customSource
 */
OnsiteSubscriptionCreateQueryResourceObjectAttributes.prototype.customSource = undefined;

/**
 * Email address to create subscription and email consent record for.
 * @member {String} email
 */
OnsiteSubscriptionCreateQueryResourceObjectAttributes.prototype.email = undefined;

/**
 * Phone number to create subscription and SMS consent record for, in E.164 format.
 * @member {String} phoneNumber
 */
OnsiteSubscriptionCreateQueryResourceObjectAttributes.prototype.phoneNumber = undefined;

/**
 * Profile properties to set on the newly subscribed profile.
 * @member {Object} properties
 */
OnsiteSubscriptionCreateQueryResourceObjectAttributes.prototype.properties = undefined;

