/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-08-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {BackInStockSubscriptionEnum} from './BackInStockSubscriptionEnum.js';
import {ServerBISSubscriptionCreateQueryResourceObjectAttributes} from './ServerBISSubscriptionCreateQueryResourceObjectAttributes.js';
import {ServerBISSubscriptionCreateQueryResourceObjectRelationships} from './ServerBISSubscriptionCreateQueryResourceObjectRelationships.js';

/**
 * The ServerBISSubscriptionCreateQueryResourceObject model module.
 * @module model/ServerBISSubscriptionCreateQueryResourceObject
 * @version 2023-08-15
 */
export class ServerBISSubscriptionCreateQueryResourceObject {
  /**
   * Constructs a new <code>ServerBISSubscriptionCreateQueryResourceObject</code>.
   * @alias module:model/ServerBISSubscriptionCreateQueryResourceObject
   * @class
   * @param type {module:model/BackInStockSubscriptionEnum} 
   * @param attributes {module:model/ServerBISSubscriptionCreateQueryResourceObjectAttributes} 
   */
  constructor(type, attributes) {
    this.type = type;
    this.attributes = attributes;
  }

  /**
   * Constructs a <code>ServerBISSubscriptionCreateQueryResourceObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServerBISSubscriptionCreateQueryResourceObject} obj Optional instance to populate.
   * @return {module:model/ServerBISSubscriptionCreateQueryResourceObject} The populated <code>ServerBISSubscriptionCreateQueryResourceObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServerBISSubscriptionCreateQueryResourceObject();
      if (data.hasOwnProperty('type'))
        obj.type = BackInStockSubscriptionEnum.constructFromObject(data['type']);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = ServerBISSubscriptionCreateQueryResourceObjectAttributes.constructFromObject(data['attributes']);
      if (data.hasOwnProperty('relationships'))
        obj.relationships = ServerBISSubscriptionCreateQueryResourceObjectRelationships.constructFromObject(data['relationships']);
    }
    return obj;
  }
}

/**
 * @member {module:model/BackInStockSubscriptionEnum} type
 */
ServerBISSubscriptionCreateQueryResourceObject.prototype.type = undefined;

/**
 * @member {module:model/ServerBISSubscriptionCreateQueryResourceObjectAttributes} attributes
 */
ServerBISSubscriptionCreateQueryResourceObject.prototype.attributes = undefined;

/**
 * @member {module:model/ServerBISSubscriptionCreateQueryResourceObjectRelationships} relationships
 */
ServerBISSubscriptionCreateQueryResourceObject.prototype.relationships = undefined;

