/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-08-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {ServerBISSubscriptionCreateQueryResourceObjectAttributesProfile} from './ServerBISSubscriptionCreateQueryResourceObjectAttributesProfile.js';

/**
 * The ServerBISSubscriptionCreateQueryResourceObjectAttributes model module.
 * @module model/ServerBISSubscriptionCreateQueryResourceObjectAttributes
 * @version 2023-08-15
 */
export class ServerBISSubscriptionCreateQueryResourceObjectAttributes {
  /**
   * Constructs a new <code>ServerBISSubscriptionCreateQueryResourceObjectAttributes</code>.
   * @alias module:model/ServerBISSubscriptionCreateQueryResourceObjectAttributes
   * @class
   * @param channels {Array.<module:model/ServerBISSubscriptionCreateQueryResourceObjectAttributes.ChannelsEnum>} The channel(s) through which the profile would like to receive the back in stock notification. This can be leveraged within a back in stock flow to notify the subscriber through their preferred channel(s).
   */
  constructor(channels) {
    this.channels = channels;
  }

  /**
   * Constructs a <code>ServerBISSubscriptionCreateQueryResourceObjectAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServerBISSubscriptionCreateQueryResourceObjectAttributes} obj Optional instance to populate.
   * @return {module:model/ServerBISSubscriptionCreateQueryResourceObjectAttributes} The populated <code>ServerBISSubscriptionCreateQueryResourceObjectAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServerBISSubscriptionCreateQueryResourceObjectAttributes();
      if (data.hasOwnProperty('channels'))
        obj.channels = ApiClient.convertToType(data['channels'], ['String']);
      if (data.hasOwnProperty('profile'))
        obj.profile = ServerBISSubscriptionCreateQueryResourceObjectAttributesProfile.constructFromObject(data['profile']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>channels</code> property.
 * @enum {String}
 * @readonly
 */
ServerBISSubscriptionCreateQueryResourceObjectAttributes.ChannelsEnum = {
  /**
   * value: "EMAIL"
   * @const
   */
  EMAIL: "EMAIL",

  /**
   * value: "PUSH"
   * @const
   */
  PUSH: "PUSH",

  /**
   * value: "SMS"
   * @const
   */
  SMS: "SMS"
};
/**
 * The channel(s) through which the profile would like to receive the back in stock notification. This can be leveraged within a back in stock flow to notify the subscriber through their preferred channel(s).
 * @member {Array.<module:model/ServerBISSubscriptionCreateQueryResourceObjectAttributes.ChannelsEnum>} channels
 */
ServerBISSubscriptionCreateQueryResourceObjectAttributes.prototype.channels = undefined;

/**
 * @member {module:model/ServerBISSubscriptionCreateQueryResourceObjectAttributesProfile} profile
 */
ServerBISSubscriptionCreateQueryResourceObjectAttributes.prototype.profile = undefined;

