/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-02-22
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The SubscriptionChannels model module.
 * @module model/SubscriptionChannels
 * @version 2023-02-22
 */
export class SubscriptionChannels {
  /**
   * Constructs a new <code>SubscriptionChannels</code>.
   * @alias module:model/SubscriptionChannels
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SubscriptionChannels</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionChannels} obj Optional instance to populate.
   * @return {module:model/SubscriptionChannels} The populated <code>SubscriptionChannels</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionChannels();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], ['String']);
      if (data.hasOwnProperty('sms'))
        obj.sms = ApiClient.convertToType(data['sms'], ['String']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>email</code> property.
 * @enum {String}
 * @readonly
 */
SubscriptionChannels.EmailEnum = {
  /**
   * value: "MARKETING"
   * @const
   */
  MARKETING: "MARKETING"
};
/**
 * The communication types to subscribe to on the \"EMAIL\" Channel. Currently supports \"MARKETING\".
 * @member {Array.<module:model/SubscriptionChannels.EmailEnum>} email
 */
SubscriptionChannels.prototype.email = undefined;

/**
 * Allowed values for the <code>sms</code> property.
 * @enum {String}
 * @readonly
 */
SubscriptionChannels.SmsEnum = {
  /**
   * value: "MARKETING"
   * @const
   */
  MARKETING: "MARKETING"
};
/**
 * The communication types to subscribe to on the \"SMS\" Channel. Currently supports \"MARKETING\".
 * @member {Array.<module:model/SubscriptionChannels.SmsEnum>} sms
 */
SubscriptionChannels.prototype.sms = undefined;

