/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-08-15
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {ListEnum} from './ListEnum.js';

/**
 * The SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData model module.
 * @module model/SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData
 * @version 2023-08-15
 */
export class SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData {
  /**
   * Constructs a new <code>SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData</code>.
   * @alias module:model/SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData
   * @class
   * @param type {module:model/ListEnum} 
   * @param id {String} 
   */
  constructor(type, id) {
    this.type = type;
    this.id = id;
  }

  /**
   * Constructs a <code>SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData} obj Optional instance to populate.
   * @return {module:model/SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData} The populated <code>SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData();
      if (data.hasOwnProperty('type'))
        obj.type = ListEnum.constructFromObject(data['type']);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/ListEnum} type
 */
SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData.prototype.type = undefined;

/**
 * @member {String} id
 */
SubscriptionCreateJobCreateQueryResourceObjectRelationshipsListData.prototype.id = undefined;

