/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-02-22
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {Suppression} from './Suppression.js';

/**
 * The SuppressionCreateJobCreateQueryResourceObjectAttributes model module.
 * @module model/SuppressionCreateJobCreateQueryResourceObjectAttributes
 * @version 2023-02-22
 */
export class SuppressionCreateJobCreateQueryResourceObjectAttributes {
  /**
   * Constructs a new <code>SuppressionCreateJobCreateQueryResourceObjectAttributes</code>.
   * @alias module:model/SuppressionCreateJobCreateQueryResourceObjectAttributes
   * @class
   * @param suppressions {Array.<module:model/Suppression>} One or more suppressions to be created.
   */
  constructor(suppressions) {
    this.suppressions = suppressions;
  }

  /**
   * Constructs a <code>SuppressionCreateJobCreateQueryResourceObjectAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuppressionCreateJobCreateQueryResourceObjectAttributes} obj Optional instance to populate.
   * @return {module:model/SuppressionCreateJobCreateQueryResourceObjectAttributes} The populated <code>SuppressionCreateJobCreateQueryResourceObjectAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SuppressionCreateJobCreateQueryResourceObjectAttributes();
      if (data.hasOwnProperty('suppressions'))
        obj.suppressions = ApiClient.convertToType(data['suppressions'], [Suppression]);
    }
    return obj;
  }
}

/**
 * One or more suppressions to be created.
 * @member {Array.<module:model/Suppression>} suppressions
 */
SuppressionCreateJobCreateQueryResourceObjectAttributes.prototype.suppressions = undefined;

