/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-02-22
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {ProfileUnsubscriptionBulkCreateJobEnum} from './ProfileUnsubscriptionBulkCreateJobEnum.js';
import {UnsubscriptionCreateJobCreateQueryResourceObjectAttributes} from './UnsubscriptionCreateJobCreateQueryResourceObjectAttributes.js';

/**
 * The UnsubscriptionCreateJobCreateQueryResourceObject model module.
 * @module model/UnsubscriptionCreateJobCreateQueryResourceObject
 * @version 2023-02-22
 */
export class UnsubscriptionCreateJobCreateQueryResourceObject {
  /**
   * Constructs a new <code>UnsubscriptionCreateJobCreateQueryResourceObject</code>.
   * @alias module:model/UnsubscriptionCreateJobCreateQueryResourceObject
   * @class
   * @param type {module:model/ProfileUnsubscriptionBulkCreateJobEnum} 
   * @param attributes {module:model/UnsubscriptionCreateJobCreateQueryResourceObjectAttributes} 
   */
  constructor(type, attributes) {
    this.type = type;
    this.attributes = attributes;
  }

  /**
   * Constructs a <code>UnsubscriptionCreateJobCreateQueryResourceObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnsubscriptionCreateJobCreateQueryResourceObject} obj Optional instance to populate.
   * @return {module:model/UnsubscriptionCreateJobCreateQueryResourceObject} The populated <code>UnsubscriptionCreateJobCreateQueryResourceObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UnsubscriptionCreateJobCreateQueryResourceObject();
      if (data.hasOwnProperty('type'))
        obj.type = ProfileUnsubscriptionBulkCreateJobEnum.constructFromObject(data['type']);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = UnsubscriptionCreateJobCreateQueryResourceObjectAttributes.constructFromObject(data['attributes']);
    }
    return obj;
  }
}

/**
 * @member {module:model/ProfileUnsubscriptionBulkCreateJobEnum} type
 */
UnsubscriptionCreateJobCreateQueryResourceObject.prototype.type = undefined;

/**
 * @member {module:model/UnsubscriptionCreateJobCreateQueryResourceObjectAttributes} attributes
 */
UnsubscriptionCreateJobCreateQueryResourceObject.prototype.attributes = undefined;

