/*
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * OpenAPI spec version: 2023-01-24
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient.js';
import {AudiencesSubObject} from './model/AudiencesSubObject.js';
import {CampaignCloneQuery} from './model/CampaignCloneQuery.js';
import {CampaignCloneQueryAsSubResource} from './model/CampaignCloneQueryAsSubResource.js';
import {CampaignCloneQueryAsSubResourceAttributes} from './model/CampaignCloneQueryAsSubResourceAttributes.js';
import {CampaignCreateQuery} from './model/CampaignCreateQuery.js';
import {CampaignCreateQueryAsSubResource} from './model/CampaignCreateQueryAsSubResource.js';
import {CampaignCreateQueryAsSubResourceAttributes} from './model/CampaignCreateQueryAsSubResourceAttributes.js';
import {CampaignMessageAssignTemplateQuery} from './model/CampaignMessageAssignTemplateQuery.js';
import {CampaignMessageAssignTemplateQueryAsSubResource} from './model/CampaignMessageAssignTemplateQueryAsSubResource.js';
import {CampaignMessageAssignTemplateQueryAsSubResourceAttributes} from './model/CampaignMessageAssignTemplateQueryAsSubResourceAttributes.js';
import {CampaignMessagePartialUpdateQuery} from './model/CampaignMessagePartialUpdateQuery.js';
import {CampaignMessagePartialUpdateQueryAsSubResource} from './model/CampaignMessagePartialUpdateQueryAsSubResource.js';
import {CampaignMessagePartialUpdateQueryAsSubResourceAttributes} from './model/CampaignMessagePartialUpdateQueryAsSubResourceAttributes.js';
import {CampaignPartialUpdateQuery} from './model/CampaignPartialUpdateQuery.js';
import {CampaignPartialUpdateQueryAsSubResource} from './model/CampaignPartialUpdateQueryAsSubResource.js';
import {CampaignPartialUpdateQueryAsSubResourceAttributes} from './model/CampaignPartialUpdateQueryAsSubResourceAttributes.js';
import {CampaignSendJobCreateQuery} from './model/CampaignSendJobCreateQuery.js';
import {CampaignSendJobCreateQueryAsSubResource} from './model/CampaignSendJobCreateQueryAsSubResource.js';
import {CampaignSendJobCreateQueryAsSubResourceAttributes} from './model/CampaignSendJobCreateQueryAsSubResourceAttributes.js';
import {CampaignSendJobPartialUpdateQuery} from './model/CampaignSendJobPartialUpdateQuery.js';
import {CampaignSendJobPartialUpdateQueryAsSubResource} from './model/CampaignSendJobPartialUpdateQueryAsSubResource.js';
import {CampaignSendJobPartialUpdateQueryAsSubResourceAttributes} from './model/CampaignSendJobPartialUpdateQueryAsSubResourceAttributes.js';
import {CatalogCategoryCreateJobCreateQuery} from './model/CatalogCategoryCreateJobCreateQuery.js';
import {CatalogCategoryCreateJobCreateQueryAsSubResource} from './model/CatalogCategoryCreateJobCreateQueryAsSubResource.js';
import {CatalogCategoryCreateJobCreateQueryAsSubResourceAttributes} from './model/CatalogCategoryCreateJobCreateQueryAsSubResourceAttributes.js';
import {CatalogCategoryCreateQuery} from './model/CatalogCategoryCreateQuery.js';
import {CatalogCategoryCreateQueryAsSubResource} from './model/CatalogCategoryCreateQueryAsSubResource.js';
import {CatalogCategoryCreateQueryAsSubResourceAttributes} from './model/CatalogCategoryCreateQueryAsSubResourceAttributes.js';
import {CatalogCategoryDeleteJobCreateQuery} from './model/CatalogCategoryDeleteJobCreateQuery.js';
import {CatalogCategoryDeleteJobCreateQueryAsSubResource} from './model/CatalogCategoryDeleteJobCreateQueryAsSubResource.js';
import {CatalogCategoryDeleteJobCreateQueryAsSubResourceAttributes} from './model/CatalogCategoryDeleteJobCreateQueryAsSubResourceAttributes.js';
import {CatalogCategoryDeleteQueryAsSubResource} from './model/CatalogCategoryDeleteQueryAsSubResource.js';
import {CatalogCategoryItemOp} from './model/CatalogCategoryItemOp.js';
import {CatalogCategoryUpdateJobCreateQuery} from './model/CatalogCategoryUpdateJobCreateQuery.js';
import {CatalogCategoryUpdateJobCreateQueryAsSubResource} from './model/CatalogCategoryUpdateJobCreateQueryAsSubResource.js';
import {CatalogCategoryUpdateJobCreateQueryAsSubResourceAttributes} from './model/CatalogCategoryUpdateJobCreateQueryAsSubResourceAttributes.js';
import {CatalogCategoryUpdateQuery} from './model/CatalogCategoryUpdateQuery.js';
import {CatalogCategoryUpdateQueryAsSubResource} from './model/CatalogCategoryUpdateQueryAsSubResource.js';
import {CatalogCategoryUpdateQueryAsSubResourceAttributes} from './model/CatalogCategoryUpdateQueryAsSubResourceAttributes.js';
import {CatalogItemCategoryOp} from './model/CatalogItemCategoryOp.js';
import {CatalogItemCreateJobCreateQuery} from './model/CatalogItemCreateJobCreateQuery.js';
import {CatalogItemCreateJobCreateQueryAsSubResource} from './model/CatalogItemCreateJobCreateQueryAsSubResource.js';
import {CatalogItemCreateJobCreateQueryAsSubResourceAttributes} from './model/CatalogItemCreateJobCreateQueryAsSubResourceAttributes.js';
import {CatalogItemCreateQuery} from './model/CatalogItemCreateQuery.js';
import {CatalogItemCreateQueryAsSubResource} from './model/CatalogItemCreateQueryAsSubResource.js';
import {CatalogItemCreateQueryAsSubResourceAttributes} from './model/CatalogItemCreateQueryAsSubResourceAttributes.js';
import {CatalogItemCreateQueryAsSubResourceRelationships} from './model/CatalogItemCreateQueryAsSubResourceRelationships.js';
import {CatalogItemCreateQueryAsSubResourceRelationshipsCategories} from './model/CatalogItemCreateQueryAsSubResourceRelationshipsCategories.js';
import {CatalogItemCreateQueryAsSubResourceRelationshipsCategoriesData} from './model/CatalogItemCreateQueryAsSubResourceRelationshipsCategoriesData.js';
import {CatalogItemDeleteJobCreateQuery} from './model/CatalogItemDeleteJobCreateQuery.js';
import {CatalogItemDeleteJobCreateQueryAsSubResource} from './model/CatalogItemDeleteJobCreateQueryAsSubResource.js';
import {CatalogItemDeleteJobCreateQueryAsSubResourceAttributes} from './model/CatalogItemDeleteJobCreateQueryAsSubResourceAttributes.js';
import {CatalogItemDeleteQueryAsSubResource} from './model/CatalogItemDeleteQueryAsSubResource.js';
import {CatalogItemUpdateJobCreateQuery} from './model/CatalogItemUpdateJobCreateQuery.js';
import {CatalogItemUpdateJobCreateQueryAsSubResource} from './model/CatalogItemUpdateJobCreateQueryAsSubResource.js';
import {CatalogItemUpdateJobCreateQueryAsSubResourceAttributes} from './model/CatalogItemUpdateJobCreateQueryAsSubResourceAttributes.js';
import {CatalogItemUpdateQuery} from './model/CatalogItemUpdateQuery.js';
import {CatalogItemUpdateQueryAsSubResource} from './model/CatalogItemUpdateQueryAsSubResource.js';
import {CatalogItemUpdateQueryAsSubResourceAttributes} from './model/CatalogItemUpdateQueryAsSubResourceAttributes.js';
import {CatalogJobErrorPayload} from './model/CatalogJobErrorPayload.js';
import {CatalogVariantCreateJobCreateQuery} from './model/CatalogVariantCreateJobCreateQuery.js';
import {CatalogVariantCreateJobCreateQueryAsSubResource} from './model/CatalogVariantCreateJobCreateQueryAsSubResource.js';
import {CatalogVariantCreateJobCreateQueryAsSubResourceAttributes} from './model/CatalogVariantCreateJobCreateQueryAsSubResourceAttributes.js';
import {CatalogVariantCreateQuery} from './model/CatalogVariantCreateQuery.js';
import {CatalogVariantCreateQueryAsSubResource} from './model/CatalogVariantCreateQueryAsSubResource.js';
import {CatalogVariantCreateQueryAsSubResourceAttributes} from './model/CatalogVariantCreateQueryAsSubResourceAttributes.js';
import {CatalogVariantCreateQueryAsSubResourceRelationships} from './model/CatalogVariantCreateQueryAsSubResourceRelationships.js';
import {CatalogVariantCreateQueryAsSubResourceRelationshipsItems} from './model/CatalogVariantCreateQueryAsSubResourceRelationshipsItems.js';
import {CatalogVariantCreateQueryAsSubResourceRelationshipsItemsData} from './model/CatalogVariantCreateQueryAsSubResourceRelationshipsItemsData.js';
import {CatalogVariantDeleteJobCreateQuery} from './model/CatalogVariantDeleteJobCreateQuery.js';
import {CatalogVariantDeleteJobCreateQueryAsSubResource} from './model/CatalogVariantDeleteJobCreateQueryAsSubResource.js';
import {CatalogVariantDeleteJobCreateQueryAsSubResourceAttributes} from './model/CatalogVariantDeleteJobCreateQueryAsSubResourceAttributes.js';
import {CatalogVariantDeleteQueryAsSubResource} from './model/CatalogVariantDeleteQueryAsSubResource.js';
import {CatalogVariantUpdateJobCreateQuery} from './model/CatalogVariantUpdateJobCreateQuery.js';
import {CatalogVariantUpdateJobCreateQueryAsSubResource} from './model/CatalogVariantUpdateJobCreateQueryAsSubResource.js';
import {CatalogVariantUpdateJobCreateQueryAsSubResourceAttributes} from './model/CatalogVariantUpdateJobCreateQueryAsSubResourceAttributes.js';
import {CatalogVariantUpdateQuery} from './model/CatalogVariantUpdateQuery.js';
import {CatalogVariantUpdateQueryAsSubResource} from './model/CatalogVariantUpdateQueryAsSubResource.js';
import {CatalogVariantUpdateQueryAsSubResourceAttributes} from './model/CatalogVariantUpdateQueryAsSubResourceAttributes.js';
import {ContentSubObject} from './model/ContentSubObject.js';
import {DataPrivacyCreateDeletionJobQuery} from './model/DataPrivacyCreateDeletionJobQuery.js';
import {DataPrivacyCreateDeletionJobQueryAsSubResource} from './model/DataPrivacyCreateDeletionJobQueryAsSubResource.js';
import {DataPrivacyCreateDeletionJobQueryAsSubResourceAttributes} from './model/DataPrivacyCreateDeletionJobQueryAsSubResourceAttributes.js';
import {EmailMessageContent} from './model/EmailMessageContent.js';
import {EmailTrackingOptions} from './model/EmailTrackingOptions.js';
import {ErrorSource} from './model/ErrorSource.js';
import {EventCreateQuery} from './model/EventCreateQuery.js';
import {EventCreateQueryAsSubResource} from './model/EventCreateQueryAsSubResource.js';
import {EventCreateQueryAsSubResourceAttributes} from './model/EventCreateQueryAsSubResourceAttributes.js';
import {FlowUpdateQuery} from './model/FlowUpdateQuery.js';
import {FlowUpdateQueryAsSubResource} from './model/FlowUpdateQueryAsSubResource.js';
import {FlowUpdateQueryAsSubResourceAttributes} from './model/FlowUpdateQueryAsSubResourceAttributes.js';
import {IncludedCategories} from './model/IncludedCategories.js';
import {IncludedCategoriesAttributes} from './model/IncludedCategoriesAttributes.js';
import {IncludedFlowAction} from './model/IncludedFlowAction.js';
import {IncludedFlowActions} from './model/IncludedFlowActions.js';
import {IncludedFlowActionsAttributes} from './model/IncludedFlowActionsAttributes.js';
import {IncludedFlowMessages} from './model/IncludedFlowMessages.js';
import {IncludedFlowMessagesAttributes} from './model/IncludedFlowMessagesAttributes.js';
import {IncludedFlows} from './model/IncludedFlows.js';
import {IncludedFlowsAttributes} from './model/IncludedFlowsAttributes.js';
import {IncludedItems} from './model/IncludedItems.js';
import {IncludedItemsAttributes} from './model/IncludedItemsAttributes.js';
import {IncludedLists} from './model/IncludedLists.js';
import {IncludedListsAttributes} from './model/IncludedListsAttributes.js';
import {IncludedMetrics} from './model/IncludedMetrics.js';
import {IncludedMetricsAttributes} from './model/IncludedMetricsAttributes.js';
import {IncludedProfiles} from './model/IncludedProfiles.js';
import {IncludedProfilesAttributes} from './model/IncludedProfilesAttributes.js';
import {IncludedSegments} from './model/IncludedSegments.js';
import {IncludedVariants} from './model/IncludedVariants.js';
import {IncludedVariantsAttributes} from './model/IncludedVariantsAttributes.js';
import {IncludedVariantsLinks} from './model/IncludedVariantsLinks.js';
import {InlineResponse4XX} from './model/InlineResponse4XX.js';
import {InlineResponse4XXErrors} from './model/InlineResponse4XXErrors.js';
import {InlineResponse4XXSource} from './model/InlineResponse4XXSource.js';
import {ListCreateQuery} from './model/ListCreateQuery.js';
import {ListCreateQueryAsSubResource} from './model/ListCreateQueryAsSubResource.js';
import {ListCreateQueryAsSubResourceAttributes} from './model/ListCreateQueryAsSubResourceAttributes.js';
import {ListMembersAddQuery} from './model/ListMembersAddQuery.js';
import {ListMembersAddQueryData} from './model/ListMembersAddQueryData.js';
import {ListMembersDeleteQuery} from './model/ListMembersDeleteQuery.js';
import {ListPartialUpdateQuery} from './model/ListPartialUpdateQuery.js';
import {ListPartialUpdateQueryAsSubResource} from './model/ListPartialUpdateQueryAsSubResource.js';
import {MetricAggregateQuery} from './model/MetricAggregateQuery.js';
import {MetricAggregateQueryAsSubResource} from './model/MetricAggregateQueryAsSubResource.js';
import {MetricAggregateQueryAsSubResourceAttributes} from './model/MetricAggregateQueryAsSubResourceAttributes.js';
import {MetricAggregateRowDTO} from './model/MetricAggregateRowDTO.js';
import {MetricCreateQuery} from './model/MetricCreateQuery.js';
import {OneOfIncludedFlowActionsAttributesTrackingOptions} from './model/OneOfIncludedFlowActionsAttributesTrackingOptions.js';
import {OneOfIncludedFlowMessagesAttributesContent} from './model/OneOfIncludedFlowMessagesAttributesContent.js';
import {OneOfProfileLocationLatitude} from './model/OneOfProfileLocationLatitude.js';
import {OneOfProfileLocationLongitude} from './model/OneOfProfileLocationLongitude.js';
import {OnsiteProfileCreateQuery} from './model/OnsiteProfileCreateQuery.js';
import {OnsiteProfileCreateQueryAsSubResource} from './model/OnsiteProfileCreateQueryAsSubResource.js';
import {OnsiteProfileMeta} from './model/OnsiteProfileMeta.js';
import {OnsiteProfileMetaIdentifiers} from './model/OnsiteProfileMetaIdentifiers.js';
import {OnsiteSubscriptionCreateQuery} from './model/OnsiteSubscriptionCreateQuery.js';
import {OnsiteSubscriptionCreateQueryAsSubResource} from './model/OnsiteSubscriptionCreateQueryAsSubResource.js';
import {OnsiteSubscriptionCreateQueryAsSubResourceAttributes} from './model/OnsiteSubscriptionCreateQueryAsSubResourceAttributes.js';
import {ProfileCreateQuery} from './model/ProfileCreateQuery.js';
import {ProfileCreateQueryAsSubResource} from './model/ProfileCreateQueryAsSubResource.js';
import {ProfileCreateQueryAsSubResourceAttributes} from './model/ProfileCreateQueryAsSubResourceAttributes.js';
import {ProfileLocation} from './model/ProfileLocation.js';
import {ProfilePartialUpdateQuery} from './model/ProfilePartialUpdateQuery.js';
import {ProfilePartialUpdateQueryAsSubResource} from './model/ProfilePartialUpdateQueryAsSubResource.js';
import {SMSMessageContent} from './model/SMSMessageContent.js';
import {SMSRenderOptions} from './model/SMSRenderOptions.js';
import {SMSTrackingOptions} from './model/SMSTrackingOptions.js';
import {SegmentPartialUpdateQuery} from './model/SegmentPartialUpdateQuery.js';
import {SegmentPartialUpdateQueryAsSubResource} from './model/SegmentPartialUpdateQueryAsSubResource.js';
import {SendOptions} from './model/SendOptions.js';
import {SendOptionsSubObject} from './model/SendOptionsSubObject.js';
import {SendStrategySubObject} from './model/SendStrategySubObject.js';
import {SendTimeSubObject} from './model/SendTimeSubObject.js';
import {StaticScheduleOptions} from './model/StaticScheduleOptions.js';
import {Subscription} from './model/Subscription.js';
import {SubscriptionCreateJobCreateQuery} from './model/SubscriptionCreateJobCreateQuery.js';
import {SubscriptionCreateJobCreateQueryAsSubResource} from './model/SubscriptionCreateJobCreateQueryAsSubResource.js';
import {SubscriptionCreateJobCreateQueryAsSubResourceAttributes} from './model/SubscriptionCreateJobCreateQueryAsSubResourceAttributes.js';
import {Suppression} from './model/Suppression.js';
import {SuppressionCreateJobCreateQuery} from './model/SuppressionCreateJobCreateQuery.js';
import {SuppressionCreateJobCreateQueryAsSubResource} from './model/SuppressionCreateJobCreateQueryAsSubResource.js';
import {SuppressionCreateJobCreateQueryAsSubResourceAttributes} from './model/SuppressionCreateJobCreateQueryAsSubResourceAttributes.js';
import {TagCreateQuery} from './model/TagCreateQuery.js';
import {TagCreateQueryAsSubResource} from './model/TagCreateQueryAsSubResource.js';
import {TagCreateQueryAsSubResourceAttributes} from './model/TagCreateQueryAsSubResourceAttributes.js';
import {TagGroupCreateQuery} from './model/TagGroupCreateQuery.js';
import {TagGroupCreateQueryAsSubResource} from './model/TagGroupCreateQueryAsSubResource.js';
import {TagGroupCreateQueryAsSubResourceAttributes} from './model/TagGroupCreateQueryAsSubResourceAttributes.js';
import {TagGroupUpdateQuery} from './model/TagGroupUpdateQuery.js';
import {TagGroupUpdateQueryAsSubResource} from './model/TagGroupUpdateQueryAsSubResource.js';
import {TagGroupUpdateQueryAsSubResourceAttributes} from './model/TagGroupUpdateQueryAsSubResourceAttributes.js';
import {TagSegmentOp} from './model/TagSegmentOp.js';
import {TagSegmentOpData} from './model/TagSegmentOpData.js';
import {TagUpdateQuery} from './model/TagUpdateQuery.js';
import {TagUpdateQueryAsSubResource} from './model/TagUpdateQueryAsSubResource.js';
import {TagUpdateQueryAsSubResourceAttributes} from './model/TagUpdateQueryAsSubResourceAttributes.js';
import {TemplateCloneQuery} from './model/TemplateCloneQuery.js';
import {TemplateCloneQueryAsSubResource} from './model/TemplateCloneQueryAsSubResource.js';
import {TemplateCloneQueryAsSubResourceAttributes} from './model/TemplateCloneQueryAsSubResourceAttributes.js';
import {TemplateCreateQuery} from './model/TemplateCreateQuery.js';
import {TemplateCreateQueryAsSubResource} from './model/TemplateCreateQueryAsSubResource.js';
import {TemplateCreateQueryAsSubResourceAttributes} from './model/TemplateCreateQueryAsSubResourceAttributes.js';
import {TemplateRenderQuery} from './model/TemplateRenderQuery.js';
import {TemplateRenderQueryAsSubResource} from './model/TemplateRenderQueryAsSubResource.js';
import {TemplateRenderQueryAsSubResourceAttributes} from './model/TemplateRenderQueryAsSubResourceAttributes.js';
import {TemplateUpdateQuery} from './model/TemplateUpdateQuery.js';
import {TemplateUpdateQueryAsSubResource} from './model/TemplateUpdateQueryAsSubResource.js';
import {TemplateUpdateQueryAsSubResourceAttributes} from './model/TemplateUpdateQueryAsSubResourceAttributes.js';
import {ThrottledScheduleOptions} from './model/ThrottledScheduleOptions.js';
import {TrackingOptionsSubObject} from './model/TrackingOptionsSubObject.js';
import {UTMParamsSubObject} from './model/UTMParamsSubObject.js';
import {UnsubscriptionCreateJobCreateQuery} from './model/UnsubscriptionCreateJobCreateQuery.js';
import {UnsubscriptionCreateJobCreateQueryAsSubResource} from './model/UnsubscriptionCreateJobCreateQueryAsSubResource.js';
import {UnsubscriptionCreateJobCreateQueryAsSubResourceAttributes} from './model/UnsubscriptionCreateJobCreateQueryAsSubResourceAttributes.js';
import {UnsuppressionCreateJobCreateQuery} from './model/UnsuppressionCreateJobCreateQuery.js';
import {UnsuppressionCreateJobCreateQueryAsSubResource} from './model/UnsuppressionCreateJobCreateQueryAsSubResource.js';
import {UnsuppressionCreateJobCreateQueryAsSubResourceAttributes} from './model/UnsuppressionCreateJobCreateQueryAsSubResourceAttributes.js';
import {UtmParamInfo} from './model/UtmParamInfo.js';
import {V2TemplateRenderQueryAsSubResource} from './model/V2TemplateRenderQueryAsSubResource.js';
import {CatalogsApi} from './api/CatalogsApi.js';
import {ClientApi} from './api/ClientApi.js';
import {DataPrivacyApi} from './api/DataPrivacyApi.js';
import {EventsApi} from './api/EventsApi.js';
import {FlowsApi} from './api/FlowsApi.js';
import {ListsApi} from './api/ListsApi.js';
import {MetricsApi} from './api/MetricsApi.js';
import {ProfilesApi} from './api/ProfilesApi.js';
import {SegmentsApi} from './api/SegmentsApi.js';
import {TagsApi} from './api/TagsApi.js';
import {TemplatesApi} from './api/TemplatesApi.js';

import {
        Catalogs,
        Client,
        DataPrivacy,
        Events,
        Flows,
        Lists,
        Metrics,
        Profiles,
        Segments,
        Tags,
        Templates,
    ConfigWrapper,
} from "./clientWrapper.js";

/**
* The_Klaviyo_REST_API__Please_visit_httpsdevelopers_klaviyo_com_for_more_details_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var KlaviyoApi = require('index'); // See note below*.
* var xxxSvc = new KlaviyoApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new KlaviyoApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new KlaviyoApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new KlaviyoApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2023-01-24
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AudiencesSubObject model constructor.
     * @property {module:model/AudiencesSubObject}
     */
    AudiencesSubObject,

    /**
     * The CampaignCloneQuery model constructor.
     * @property {module:model/CampaignCloneQuery}
     */
    CampaignCloneQuery,

    /**
     * The CampaignCloneQueryAsSubResource model constructor.
     * @property {module:model/CampaignCloneQueryAsSubResource}
     */
    CampaignCloneQueryAsSubResource,

    /**
     * The CampaignCloneQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CampaignCloneQueryAsSubResourceAttributes}
     */
    CampaignCloneQueryAsSubResourceAttributes,

    /**
     * The CampaignCreateQuery model constructor.
     * @property {module:model/CampaignCreateQuery}
     */
    CampaignCreateQuery,

    /**
     * The CampaignCreateQueryAsSubResource model constructor.
     * @property {module:model/CampaignCreateQueryAsSubResource}
     */
    CampaignCreateQueryAsSubResource,

    /**
     * The CampaignCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CampaignCreateQueryAsSubResourceAttributes}
     */
    CampaignCreateQueryAsSubResourceAttributes,

    /**
     * The CampaignMessageAssignTemplateQuery model constructor.
     * @property {module:model/CampaignMessageAssignTemplateQuery}
     */
    CampaignMessageAssignTemplateQuery,

    /**
     * The CampaignMessageAssignTemplateQueryAsSubResource model constructor.
     * @property {module:model/CampaignMessageAssignTemplateQueryAsSubResource}
     */
    CampaignMessageAssignTemplateQueryAsSubResource,

    /**
     * The CampaignMessageAssignTemplateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CampaignMessageAssignTemplateQueryAsSubResourceAttributes}
     */
    CampaignMessageAssignTemplateQueryAsSubResourceAttributes,

    /**
     * The CampaignMessagePartialUpdateQuery model constructor.
     * @property {module:model/CampaignMessagePartialUpdateQuery}
     */
    CampaignMessagePartialUpdateQuery,

    /**
     * The CampaignMessagePartialUpdateQueryAsSubResource model constructor.
     * @property {module:model/CampaignMessagePartialUpdateQueryAsSubResource}
     */
    CampaignMessagePartialUpdateQueryAsSubResource,

    /**
     * The CampaignMessagePartialUpdateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CampaignMessagePartialUpdateQueryAsSubResourceAttributes}
     */
    CampaignMessagePartialUpdateQueryAsSubResourceAttributes,

    /**
     * The CampaignPartialUpdateQuery model constructor.
     * @property {module:model/CampaignPartialUpdateQuery}
     */
    CampaignPartialUpdateQuery,

    /**
     * The CampaignPartialUpdateQueryAsSubResource model constructor.
     * @property {module:model/CampaignPartialUpdateQueryAsSubResource}
     */
    CampaignPartialUpdateQueryAsSubResource,

    /**
     * The CampaignPartialUpdateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CampaignPartialUpdateQueryAsSubResourceAttributes}
     */
    CampaignPartialUpdateQueryAsSubResourceAttributes,

    /**
     * The CampaignSendJobCreateQuery model constructor.
     * @property {module:model/CampaignSendJobCreateQuery}
     */
    CampaignSendJobCreateQuery,

    /**
     * The CampaignSendJobCreateQueryAsSubResource model constructor.
     * @property {module:model/CampaignSendJobCreateQueryAsSubResource}
     */
    CampaignSendJobCreateQueryAsSubResource,

    /**
     * The CampaignSendJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CampaignSendJobCreateQueryAsSubResourceAttributes}
     */
    CampaignSendJobCreateQueryAsSubResourceAttributes,

    /**
     * The CampaignSendJobPartialUpdateQuery model constructor.
     * @property {module:model/CampaignSendJobPartialUpdateQuery}
     */
    CampaignSendJobPartialUpdateQuery,

    /**
     * The CampaignSendJobPartialUpdateQueryAsSubResource model constructor.
     * @property {module:model/CampaignSendJobPartialUpdateQueryAsSubResource}
     */
    CampaignSendJobPartialUpdateQueryAsSubResource,

    /**
     * The CampaignSendJobPartialUpdateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CampaignSendJobPartialUpdateQueryAsSubResourceAttributes}
     */
    CampaignSendJobPartialUpdateQueryAsSubResourceAttributes,

    /**
     * The CatalogCategoryCreateJobCreateQuery model constructor.
     * @property {module:model/CatalogCategoryCreateJobCreateQuery}
     */
    CatalogCategoryCreateJobCreateQuery,

    /**
     * The CatalogCategoryCreateJobCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogCategoryCreateJobCreateQueryAsSubResource}
     */
    CatalogCategoryCreateJobCreateQueryAsSubResource,

    /**
     * The CatalogCategoryCreateJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogCategoryCreateJobCreateQueryAsSubResourceAttributes}
     */
    CatalogCategoryCreateJobCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogCategoryCreateQuery model constructor.
     * @property {module:model/CatalogCategoryCreateQuery}
     */
    CatalogCategoryCreateQuery,

    /**
     * The CatalogCategoryCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogCategoryCreateQueryAsSubResource}
     */
    CatalogCategoryCreateQueryAsSubResource,

    /**
     * The CatalogCategoryCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogCategoryCreateQueryAsSubResourceAttributes}
     */
    CatalogCategoryCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogCategoryDeleteJobCreateQuery model constructor.
     * @property {module:model/CatalogCategoryDeleteJobCreateQuery}
     */
    CatalogCategoryDeleteJobCreateQuery,

    /**
     * The CatalogCategoryDeleteJobCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogCategoryDeleteJobCreateQueryAsSubResource}
     */
    CatalogCategoryDeleteJobCreateQueryAsSubResource,

    /**
     * The CatalogCategoryDeleteJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogCategoryDeleteJobCreateQueryAsSubResourceAttributes}
     */
    CatalogCategoryDeleteJobCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogCategoryDeleteQueryAsSubResource model constructor.
     * @property {module:model/CatalogCategoryDeleteQueryAsSubResource}
     */
    CatalogCategoryDeleteQueryAsSubResource,

    /**
     * The CatalogCategoryItemOp model constructor.
     * @property {module:model/CatalogCategoryItemOp}
     */
    CatalogCategoryItemOp,

    /**
     * The CatalogCategoryUpdateJobCreateQuery model constructor.
     * @property {module:model/CatalogCategoryUpdateJobCreateQuery}
     */
    CatalogCategoryUpdateJobCreateQuery,

    /**
     * The CatalogCategoryUpdateJobCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogCategoryUpdateJobCreateQueryAsSubResource}
     */
    CatalogCategoryUpdateJobCreateQueryAsSubResource,

    /**
     * The CatalogCategoryUpdateJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogCategoryUpdateJobCreateQueryAsSubResourceAttributes}
     */
    CatalogCategoryUpdateJobCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogCategoryUpdateQuery model constructor.
     * @property {module:model/CatalogCategoryUpdateQuery}
     */
    CatalogCategoryUpdateQuery,

    /**
     * The CatalogCategoryUpdateQueryAsSubResource model constructor.
     * @property {module:model/CatalogCategoryUpdateQueryAsSubResource}
     */
    CatalogCategoryUpdateQueryAsSubResource,

    /**
     * The CatalogCategoryUpdateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogCategoryUpdateQueryAsSubResourceAttributes}
     */
    CatalogCategoryUpdateQueryAsSubResourceAttributes,

    /**
     * The CatalogItemCategoryOp model constructor.
     * @property {module:model/CatalogItemCategoryOp}
     */
    CatalogItemCategoryOp,

    /**
     * The CatalogItemCreateJobCreateQuery model constructor.
     * @property {module:model/CatalogItemCreateJobCreateQuery}
     */
    CatalogItemCreateJobCreateQuery,

    /**
     * The CatalogItemCreateJobCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogItemCreateJobCreateQueryAsSubResource}
     */
    CatalogItemCreateJobCreateQueryAsSubResource,

    /**
     * The CatalogItemCreateJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogItemCreateJobCreateQueryAsSubResourceAttributes}
     */
    CatalogItemCreateJobCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogItemCreateQuery model constructor.
     * @property {module:model/CatalogItemCreateQuery}
     */
    CatalogItemCreateQuery,

    /**
     * The CatalogItemCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogItemCreateQueryAsSubResource}
     */
    CatalogItemCreateQueryAsSubResource,

    /**
     * The CatalogItemCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogItemCreateQueryAsSubResourceAttributes}
     */
    CatalogItemCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogItemCreateQueryAsSubResourceRelationships model constructor.
     * @property {module:model/CatalogItemCreateQueryAsSubResourceRelationships}
     */
    CatalogItemCreateQueryAsSubResourceRelationships,

    /**
     * The CatalogItemCreateQueryAsSubResourceRelationshipsCategories model constructor.
     * @property {module:model/CatalogItemCreateQueryAsSubResourceRelationshipsCategories}
     */
    CatalogItemCreateQueryAsSubResourceRelationshipsCategories,

    /**
     * The CatalogItemCreateQueryAsSubResourceRelationshipsCategoriesData model constructor.
     * @property {module:model/CatalogItemCreateQueryAsSubResourceRelationshipsCategoriesData}
     */
    CatalogItemCreateQueryAsSubResourceRelationshipsCategoriesData,

    /**
     * The CatalogItemDeleteJobCreateQuery model constructor.
     * @property {module:model/CatalogItemDeleteJobCreateQuery}
     */
    CatalogItemDeleteJobCreateQuery,

    /**
     * The CatalogItemDeleteJobCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogItemDeleteJobCreateQueryAsSubResource}
     */
    CatalogItemDeleteJobCreateQueryAsSubResource,

    /**
     * The CatalogItemDeleteJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogItemDeleteJobCreateQueryAsSubResourceAttributes}
     */
    CatalogItemDeleteJobCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogItemDeleteQueryAsSubResource model constructor.
     * @property {module:model/CatalogItemDeleteQueryAsSubResource}
     */
    CatalogItemDeleteQueryAsSubResource,

    /**
     * The CatalogItemUpdateJobCreateQuery model constructor.
     * @property {module:model/CatalogItemUpdateJobCreateQuery}
     */
    CatalogItemUpdateJobCreateQuery,

    /**
     * The CatalogItemUpdateJobCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogItemUpdateJobCreateQueryAsSubResource}
     */
    CatalogItemUpdateJobCreateQueryAsSubResource,

    /**
     * The CatalogItemUpdateJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogItemUpdateJobCreateQueryAsSubResourceAttributes}
     */
    CatalogItemUpdateJobCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogItemUpdateQuery model constructor.
     * @property {module:model/CatalogItemUpdateQuery}
     */
    CatalogItemUpdateQuery,

    /**
     * The CatalogItemUpdateQueryAsSubResource model constructor.
     * @property {module:model/CatalogItemUpdateQueryAsSubResource}
     */
    CatalogItemUpdateQueryAsSubResource,

    /**
     * The CatalogItemUpdateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogItemUpdateQueryAsSubResourceAttributes}
     */
    CatalogItemUpdateQueryAsSubResourceAttributes,

    /**
     * The CatalogJobErrorPayload model constructor.
     * @property {module:model/CatalogJobErrorPayload}
     */
    CatalogJobErrorPayload,

    /**
     * The CatalogVariantCreateJobCreateQuery model constructor.
     * @property {module:model/CatalogVariantCreateJobCreateQuery}
     */
    CatalogVariantCreateJobCreateQuery,

    /**
     * The CatalogVariantCreateJobCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogVariantCreateJobCreateQueryAsSubResource}
     */
    CatalogVariantCreateJobCreateQueryAsSubResource,

    /**
     * The CatalogVariantCreateJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogVariantCreateJobCreateQueryAsSubResourceAttributes}
     */
    CatalogVariantCreateJobCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogVariantCreateQuery model constructor.
     * @property {module:model/CatalogVariantCreateQuery}
     */
    CatalogVariantCreateQuery,

    /**
     * The CatalogVariantCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogVariantCreateQueryAsSubResource}
     */
    CatalogVariantCreateQueryAsSubResource,

    /**
     * The CatalogVariantCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogVariantCreateQueryAsSubResourceAttributes}
     */
    CatalogVariantCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogVariantCreateQueryAsSubResourceRelationships model constructor.
     * @property {module:model/CatalogVariantCreateQueryAsSubResourceRelationships}
     */
    CatalogVariantCreateQueryAsSubResourceRelationships,

    /**
     * The CatalogVariantCreateQueryAsSubResourceRelationshipsItems model constructor.
     * @property {module:model/CatalogVariantCreateQueryAsSubResourceRelationshipsItems}
     */
    CatalogVariantCreateQueryAsSubResourceRelationshipsItems,

    /**
     * The CatalogVariantCreateQueryAsSubResourceRelationshipsItemsData model constructor.
     * @property {module:model/CatalogVariantCreateQueryAsSubResourceRelationshipsItemsData}
     */
    CatalogVariantCreateQueryAsSubResourceRelationshipsItemsData,

    /**
     * The CatalogVariantDeleteJobCreateQuery model constructor.
     * @property {module:model/CatalogVariantDeleteJobCreateQuery}
     */
    CatalogVariantDeleteJobCreateQuery,

    /**
     * The CatalogVariantDeleteJobCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogVariantDeleteJobCreateQueryAsSubResource}
     */
    CatalogVariantDeleteJobCreateQueryAsSubResource,

    /**
     * The CatalogVariantDeleteJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogVariantDeleteJobCreateQueryAsSubResourceAttributes}
     */
    CatalogVariantDeleteJobCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogVariantDeleteQueryAsSubResource model constructor.
     * @property {module:model/CatalogVariantDeleteQueryAsSubResource}
     */
    CatalogVariantDeleteQueryAsSubResource,

    /**
     * The CatalogVariantUpdateJobCreateQuery model constructor.
     * @property {module:model/CatalogVariantUpdateJobCreateQuery}
     */
    CatalogVariantUpdateJobCreateQuery,

    /**
     * The CatalogVariantUpdateJobCreateQueryAsSubResource model constructor.
     * @property {module:model/CatalogVariantUpdateJobCreateQueryAsSubResource}
     */
    CatalogVariantUpdateJobCreateQueryAsSubResource,

    /**
     * The CatalogVariantUpdateJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogVariantUpdateJobCreateQueryAsSubResourceAttributes}
     */
    CatalogVariantUpdateJobCreateQueryAsSubResourceAttributes,

    /**
     * The CatalogVariantUpdateQuery model constructor.
     * @property {module:model/CatalogVariantUpdateQuery}
     */
    CatalogVariantUpdateQuery,

    /**
     * The CatalogVariantUpdateQueryAsSubResource model constructor.
     * @property {module:model/CatalogVariantUpdateQueryAsSubResource}
     */
    CatalogVariantUpdateQueryAsSubResource,

    /**
     * The CatalogVariantUpdateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/CatalogVariantUpdateQueryAsSubResourceAttributes}
     */
    CatalogVariantUpdateQueryAsSubResourceAttributes,

    /**
     * The ContentSubObject model constructor.
     * @property {module:model/ContentSubObject}
     */
    ContentSubObject,

    /**
     * The DataPrivacyCreateDeletionJobQuery model constructor.
     * @property {module:model/DataPrivacyCreateDeletionJobQuery}
     */
    DataPrivacyCreateDeletionJobQuery,

    /**
     * The DataPrivacyCreateDeletionJobQueryAsSubResource model constructor.
     * @property {module:model/DataPrivacyCreateDeletionJobQueryAsSubResource}
     */
    DataPrivacyCreateDeletionJobQueryAsSubResource,

    /**
     * The DataPrivacyCreateDeletionJobQueryAsSubResourceAttributes model constructor.
     * @property {module:model/DataPrivacyCreateDeletionJobQueryAsSubResourceAttributes}
     */
    DataPrivacyCreateDeletionJobQueryAsSubResourceAttributes,

    /**
     * The EmailMessageContent model constructor.
     * @property {module:model/EmailMessageContent}
     */
    EmailMessageContent,

    /**
     * The EmailTrackingOptions model constructor.
     * @property {module:model/EmailTrackingOptions}
     */
    EmailTrackingOptions,

    /**
     * The ErrorSource model constructor.
     * @property {module:model/ErrorSource}
     */
    ErrorSource,

    /**
     * The EventCreateQuery model constructor.
     * @property {module:model/EventCreateQuery}
     */
    EventCreateQuery,

    /**
     * The EventCreateQueryAsSubResource model constructor.
     * @property {module:model/EventCreateQueryAsSubResource}
     */
    EventCreateQueryAsSubResource,

    /**
     * The EventCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/EventCreateQueryAsSubResourceAttributes}
     */
    EventCreateQueryAsSubResourceAttributes,

    /**
     * The FlowUpdateQuery model constructor.
     * @property {module:model/FlowUpdateQuery}
     */
    FlowUpdateQuery,

    /**
     * The FlowUpdateQueryAsSubResource model constructor.
     * @property {module:model/FlowUpdateQueryAsSubResource}
     */
    FlowUpdateQueryAsSubResource,

    /**
     * The FlowUpdateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/FlowUpdateQueryAsSubResourceAttributes}
     */
    FlowUpdateQueryAsSubResourceAttributes,

    /**
     * The IncludedCategories model constructor.
     * @property {module:model/IncludedCategories}
     */
    IncludedCategories,

    /**
     * The IncludedCategoriesAttributes model constructor.
     * @property {module:model/IncludedCategoriesAttributes}
     */
    IncludedCategoriesAttributes,

    /**
     * The IncludedFlowAction model constructor.
     * @property {module:model/IncludedFlowAction}
     */
    IncludedFlowAction,

    /**
     * The IncludedFlowActions model constructor.
     * @property {module:model/IncludedFlowActions}
     */
    IncludedFlowActions,

    /**
     * The IncludedFlowActionsAttributes model constructor.
     * @property {module:model/IncludedFlowActionsAttributes}
     */
    IncludedFlowActionsAttributes,

    /**
     * The IncludedFlowMessages model constructor.
     * @property {module:model/IncludedFlowMessages}
     */
    IncludedFlowMessages,

    /**
     * The IncludedFlowMessagesAttributes model constructor.
     * @property {module:model/IncludedFlowMessagesAttributes}
     */
    IncludedFlowMessagesAttributes,

    /**
     * The IncludedFlows model constructor.
     * @property {module:model/IncludedFlows}
     */
    IncludedFlows,

    /**
     * The IncludedFlowsAttributes model constructor.
     * @property {module:model/IncludedFlowsAttributes}
     */
    IncludedFlowsAttributes,

    /**
     * The IncludedItems model constructor.
     * @property {module:model/IncludedItems}
     */
    IncludedItems,

    /**
     * The IncludedItemsAttributes model constructor.
     * @property {module:model/IncludedItemsAttributes}
     */
    IncludedItemsAttributes,

    /**
     * The IncludedLists model constructor.
     * @property {module:model/IncludedLists}
     */
    IncludedLists,

    /**
     * The IncludedListsAttributes model constructor.
     * @property {module:model/IncludedListsAttributes}
     */
    IncludedListsAttributes,

    /**
     * The IncludedMetrics model constructor.
     * @property {module:model/IncludedMetrics}
     */
    IncludedMetrics,

    /**
     * The IncludedMetricsAttributes model constructor.
     * @property {module:model/IncludedMetricsAttributes}
     */
    IncludedMetricsAttributes,

    /**
     * The IncludedProfiles model constructor.
     * @property {module:model/IncludedProfiles}
     */
    IncludedProfiles,

    /**
     * The IncludedProfilesAttributes model constructor.
     * @property {module:model/IncludedProfilesAttributes}
     */
    IncludedProfilesAttributes,

    /**
     * The IncludedSegments model constructor.
     * @property {module:model/IncludedSegments}
     */
    IncludedSegments,

    /**
     * The IncludedVariants model constructor.
     * @property {module:model/IncludedVariants}
     */
    IncludedVariants,

    /**
     * The IncludedVariantsAttributes model constructor.
     * @property {module:model/IncludedVariantsAttributes}
     */
    IncludedVariantsAttributes,

    /**
     * The IncludedVariantsLinks model constructor.
     * @property {module:model/IncludedVariantsLinks}
     */
    IncludedVariantsLinks,

    /**
     * The InlineResponse4XX model constructor.
     * @property {module:model/InlineResponse4XX}
     */
    InlineResponse4XX,

    /**
     * The InlineResponse4XXErrors model constructor.
     * @property {module:model/InlineResponse4XXErrors}
     */
    InlineResponse4XXErrors,

    /**
     * The InlineResponse4XXSource model constructor.
     * @property {module:model/InlineResponse4XXSource}
     */
    InlineResponse4XXSource,

    /**
     * The ListCreateQuery model constructor.
     * @property {module:model/ListCreateQuery}
     */
    ListCreateQuery,

    /**
     * The ListCreateQueryAsSubResource model constructor.
     * @property {module:model/ListCreateQueryAsSubResource}
     */
    ListCreateQueryAsSubResource,

    /**
     * The ListCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/ListCreateQueryAsSubResourceAttributes}
     */
    ListCreateQueryAsSubResourceAttributes,

    /**
     * The ListMembersAddQuery model constructor.
     * @property {module:model/ListMembersAddQuery}
     */
    ListMembersAddQuery,

    /**
     * The ListMembersAddQueryData model constructor.
     * @property {module:model/ListMembersAddQueryData}
     */
    ListMembersAddQueryData,

    /**
     * The ListMembersDeleteQuery model constructor.
     * @property {module:model/ListMembersDeleteQuery}
     */
    ListMembersDeleteQuery,

    /**
     * The ListPartialUpdateQuery model constructor.
     * @property {module:model/ListPartialUpdateQuery}
     */
    ListPartialUpdateQuery,

    /**
     * The ListPartialUpdateQueryAsSubResource model constructor.
     * @property {module:model/ListPartialUpdateQueryAsSubResource}
     */
    ListPartialUpdateQueryAsSubResource,

    /**
     * The MetricAggregateQuery model constructor.
     * @property {module:model/MetricAggregateQuery}
     */
    MetricAggregateQuery,

    /**
     * The MetricAggregateQueryAsSubResource model constructor.
     * @property {module:model/MetricAggregateQueryAsSubResource}
     */
    MetricAggregateQueryAsSubResource,

    /**
     * The MetricAggregateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/MetricAggregateQueryAsSubResourceAttributes}
     */
    MetricAggregateQueryAsSubResourceAttributes,

    /**
     * The MetricAggregateRowDTO model constructor.
     * @property {module:model/MetricAggregateRowDTO}
     */
    MetricAggregateRowDTO,

    /**
     * The MetricCreateQuery model constructor.
     * @property {module:model/MetricCreateQuery}
     */
    MetricCreateQuery,

    /**
     * The OneOfIncludedFlowActionsAttributesTrackingOptions model constructor.
     * @property {module:model/OneOfIncludedFlowActionsAttributesTrackingOptions}
     */
    OneOfIncludedFlowActionsAttributesTrackingOptions,

    /**
     * The OneOfIncludedFlowMessagesAttributesContent model constructor.
     * @property {module:model/OneOfIncludedFlowMessagesAttributesContent}
     */
    OneOfIncludedFlowMessagesAttributesContent,

    /**
     * The OneOfProfileLocationLatitude model constructor.
     * @property {module:model/OneOfProfileLocationLatitude}
     */
    OneOfProfileLocationLatitude,

    /**
     * The OneOfProfileLocationLongitude model constructor.
     * @property {module:model/OneOfProfileLocationLongitude}
     */
    OneOfProfileLocationLongitude,

    /**
     * The OnsiteProfileCreateQuery model constructor.
     * @property {module:model/OnsiteProfileCreateQuery}
     */
    OnsiteProfileCreateQuery,

    /**
     * The OnsiteProfileCreateQueryAsSubResource model constructor.
     * @property {module:model/OnsiteProfileCreateQueryAsSubResource}
     */
    OnsiteProfileCreateQueryAsSubResource,

    /**
     * The OnsiteProfileMeta model constructor.
     * @property {module:model/OnsiteProfileMeta}
     */
    OnsiteProfileMeta,

    /**
     * The OnsiteProfileMetaIdentifiers model constructor.
     * @property {module:model/OnsiteProfileMetaIdentifiers}
     */
    OnsiteProfileMetaIdentifiers,

    /**
     * The OnsiteSubscriptionCreateQuery model constructor.
     * @property {module:model/OnsiteSubscriptionCreateQuery}
     */
    OnsiteSubscriptionCreateQuery,

    /**
     * The OnsiteSubscriptionCreateQueryAsSubResource model constructor.
     * @property {module:model/OnsiteSubscriptionCreateQueryAsSubResource}
     */
    OnsiteSubscriptionCreateQueryAsSubResource,

    /**
     * The OnsiteSubscriptionCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/OnsiteSubscriptionCreateQueryAsSubResourceAttributes}
     */
    OnsiteSubscriptionCreateQueryAsSubResourceAttributes,

    /**
     * The ProfileCreateQuery model constructor.
     * @property {module:model/ProfileCreateQuery}
     */
    ProfileCreateQuery,

    /**
     * The ProfileCreateQueryAsSubResource model constructor.
     * @property {module:model/ProfileCreateQueryAsSubResource}
     */
    ProfileCreateQueryAsSubResource,

    /**
     * The ProfileCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/ProfileCreateQueryAsSubResourceAttributes}
     */
    ProfileCreateQueryAsSubResourceAttributes,

    /**
     * The ProfileLocation model constructor.
     * @property {module:model/ProfileLocation}
     */
    ProfileLocation,

    /**
     * The ProfilePartialUpdateQuery model constructor.
     * @property {module:model/ProfilePartialUpdateQuery}
     */
    ProfilePartialUpdateQuery,

    /**
     * The ProfilePartialUpdateQueryAsSubResource model constructor.
     * @property {module:model/ProfilePartialUpdateQueryAsSubResource}
     */
    ProfilePartialUpdateQueryAsSubResource,

    /**
     * The SMSMessageContent model constructor.
     * @property {module:model/SMSMessageContent}
     */
    SMSMessageContent,

    /**
     * The SMSRenderOptions model constructor.
     * @property {module:model/SMSRenderOptions}
     */
    SMSRenderOptions,

    /**
     * The SMSTrackingOptions model constructor.
     * @property {module:model/SMSTrackingOptions}
     */
    SMSTrackingOptions,

    /**
     * The SegmentPartialUpdateQuery model constructor.
     * @property {module:model/SegmentPartialUpdateQuery}
     */
    SegmentPartialUpdateQuery,

    /**
     * The SegmentPartialUpdateQueryAsSubResource model constructor.
     * @property {module:model/SegmentPartialUpdateQueryAsSubResource}
     */
    SegmentPartialUpdateQueryAsSubResource,

    /**
     * The SendOptions model constructor.
     * @property {module:model/SendOptions}
     */
    SendOptions,

    /**
     * The SendOptionsSubObject model constructor.
     * @property {module:model/SendOptionsSubObject}
     */
    SendOptionsSubObject,

    /**
     * The SendStrategySubObject model constructor.
     * @property {module:model/SendStrategySubObject}
     */
    SendStrategySubObject,

    /**
     * The SendTimeSubObject model constructor.
     * @property {module:model/SendTimeSubObject}
     */
    SendTimeSubObject,

    /**
     * The StaticScheduleOptions model constructor.
     * @property {module:model/StaticScheduleOptions}
     */
    StaticScheduleOptions,

    /**
     * The Subscription model constructor.
     * @property {module:model/Subscription}
     */
    Subscription,

    /**
     * The SubscriptionCreateJobCreateQuery model constructor.
     * @property {module:model/SubscriptionCreateJobCreateQuery}
     */
    SubscriptionCreateJobCreateQuery,

    /**
     * The SubscriptionCreateJobCreateQueryAsSubResource model constructor.
     * @property {module:model/SubscriptionCreateJobCreateQueryAsSubResource}
     */
    SubscriptionCreateJobCreateQueryAsSubResource,

    /**
     * The SubscriptionCreateJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/SubscriptionCreateJobCreateQueryAsSubResourceAttributes}
     */
    SubscriptionCreateJobCreateQueryAsSubResourceAttributes,

    /**
     * The Suppression model constructor.
     * @property {module:model/Suppression}
     */
    Suppression,

    /**
     * The SuppressionCreateJobCreateQuery model constructor.
     * @property {module:model/SuppressionCreateJobCreateQuery}
     */
    SuppressionCreateJobCreateQuery,

    /**
     * The SuppressionCreateJobCreateQueryAsSubResource model constructor.
     * @property {module:model/SuppressionCreateJobCreateQueryAsSubResource}
     */
    SuppressionCreateJobCreateQueryAsSubResource,

    /**
     * The SuppressionCreateJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/SuppressionCreateJobCreateQueryAsSubResourceAttributes}
     */
    SuppressionCreateJobCreateQueryAsSubResourceAttributes,

    /**
     * The TagCreateQuery model constructor.
     * @property {module:model/TagCreateQuery}
     */
    TagCreateQuery,

    /**
     * The TagCreateQueryAsSubResource model constructor.
     * @property {module:model/TagCreateQueryAsSubResource}
     */
    TagCreateQueryAsSubResource,

    /**
     * The TagCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/TagCreateQueryAsSubResourceAttributes}
     */
    TagCreateQueryAsSubResourceAttributes,

    /**
     * The TagGroupCreateQuery model constructor.
     * @property {module:model/TagGroupCreateQuery}
     */
    TagGroupCreateQuery,

    /**
     * The TagGroupCreateQueryAsSubResource model constructor.
     * @property {module:model/TagGroupCreateQueryAsSubResource}
     */
    TagGroupCreateQueryAsSubResource,

    /**
     * The TagGroupCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/TagGroupCreateQueryAsSubResourceAttributes}
     */
    TagGroupCreateQueryAsSubResourceAttributes,

    /**
     * The TagGroupUpdateQuery model constructor.
     * @property {module:model/TagGroupUpdateQuery}
     */
    TagGroupUpdateQuery,

    /**
     * The TagGroupUpdateQueryAsSubResource model constructor.
     * @property {module:model/TagGroupUpdateQueryAsSubResource}
     */
    TagGroupUpdateQueryAsSubResource,

    /**
     * The TagGroupUpdateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/TagGroupUpdateQueryAsSubResourceAttributes}
     */
    TagGroupUpdateQueryAsSubResourceAttributes,

    /**
     * The TagSegmentOp model constructor.
     * @property {module:model/TagSegmentOp}
     */
    TagSegmentOp,

    /**
     * The TagSegmentOpData model constructor.
     * @property {module:model/TagSegmentOpData}
     */
    TagSegmentOpData,

    /**
     * The TagUpdateQuery model constructor.
     * @property {module:model/TagUpdateQuery}
     */
    TagUpdateQuery,

    /**
     * The TagUpdateQueryAsSubResource model constructor.
     * @property {module:model/TagUpdateQueryAsSubResource}
     */
    TagUpdateQueryAsSubResource,

    /**
     * The TagUpdateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/TagUpdateQueryAsSubResourceAttributes}
     */
    TagUpdateQueryAsSubResourceAttributes,

    /**
     * The TemplateCloneQuery model constructor.
     * @property {module:model/TemplateCloneQuery}
     */
    TemplateCloneQuery,

    /**
     * The TemplateCloneQueryAsSubResource model constructor.
     * @property {module:model/TemplateCloneQueryAsSubResource}
     */
    TemplateCloneQueryAsSubResource,

    /**
     * The TemplateCloneQueryAsSubResourceAttributes model constructor.
     * @property {module:model/TemplateCloneQueryAsSubResourceAttributes}
     */
    TemplateCloneQueryAsSubResourceAttributes,

    /**
     * The TemplateCreateQuery model constructor.
     * @property {module:model/TemplateCreateQuery}
     */
    TemplateCreateQuery,

    /**
     * The TemplateCreateQueryAsSubResource model constructor.
     * @property {module:model/TemplateCreateQueryAsSubResource}
     */
    TemplateCreateQueryAsSubResource,

    /**
     * The TemplateCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/TemplateCreateQueryAsSubResourceAttributes}
     */
    TemplateCreateQueryAsSubResourceAttributes,

    /**
     * The TemplateRenderQuery model constructor.
     * @property {module:model/TemplateRenderQuery}
     */
    TemplateRenderQuery,

    /**
     * The TemplateRenderQueryAsSubResource model constructor.
     * @property {module:model/TemplateRenderQueryAsSubResource}
     */
    TemplateRenderQueryAsSubResource,

    /**
     * The TemplateRenderQueryAsSubResourceAttributes model constructor.
     * @property {module:model/TemplateRenderQueryAsSubResourceAttributes}
     */
    TemplateRenderQueryAsSubResourceAttributes,

    /**
     * The TemplateUpdateQuery model constructor.
     * @property {module:model/TemplateUpdateQuery}
     */
    TemplateUpdateQuery,

    /**
     * The TemplateUpdateQueryAsSubResource model constructor.
     * @property {module:model/TemplateUpdateQueryAsSubResource}
     */
    TemplateUpdateQueryAsSubResource,

    /**
     * The TemplateUpdateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/TemplateUpdateQueryAsSubResourceAttributes}
     */
    TemplateUpdateQueryAsSubResourceAttributes,

    /**
     * The ThrottledScheduleOptions model constructor.
     * @property {module:model/ThrottledScheduleOptions}
     */
    ThrottledScheduleOptions,

    /**
     * The TrackingOptionsSubObject model constructor.
     * @property {module:model/TrackingOptionsSubObject}
     */
    TrackingOptionsSubObject,

    /**
     * The UTMParamsSubObject model constructor.
     * @property {module:model/UTMParamsSubObject}
     */
    UTMParamsSubObject,

    /**
     * The UnsubscriptionCreateJobCreateQuery model constructor.
     * @property {module:model/UnsubscriptionCreateJobCreateQuery}
     */
    UnsubscriptionCreateJobCreateQuery,

    /**
     * The UnsubscriptionCreateJobCreateQueryAsSubResource model constructor.
     * @property {module:model/UnsubscriptionCreateJobCreateQueryAsSubResource}
     */
    UnsubscriptionCreateJobCreateQueryAsSubResource,

    /**
     * The UnsubscriptionCreateJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/UnsubscriptionCreateJobCreateQueryAsSubResourceAttributes}
     */
    UnsubscriptionCreateJobCreateQueryAsSubResourceAttributes,

    /**
     * The UnsuppressionCreateJobCreateQuery model constructor.
     * @property {module:model/UnsuppressionCreateJobCreateQuery}
     */
    UnsuppressionCreateJobCreateQuery,

    /**
     * The UnsuppressionCreateJobCreateQueryAsSubResource model constructor.
     * @property {module:model/UnsuppressionCreateJobCreateQueryAsSubResource}
     */
    UnsuppressionCreateJobCreateQueryAsSubResource,

    /**
     * The UnsuppressionCreateJobCreateQueryAsSubResourceAttributes model constructor.
     * @property {module:model/UnsuppressionCreateJobCreateQueryAsSubResourceAttributes}
     */
    UnsuppressionCreateJobCreateQueryAsSubResourceAttributes,

    /**
     * The UtmParamInfo model constructor.
     * @property {module:model/UtmParamInfo}
     */
    UtmParamInfo,

    /**
     * The V2TemplateRenderQueryAsSubResource model constructor.
     * @property {module:model/V2TemplateRenderQueryAsSubResource}
     */
    V2TemplateRenderQueryAsSubResource,


    /**
    * The CatalogsApi service constructor.
    * @property {module:api/CatalogsApi}
    */
    CatalogsApi,

    /**
     * The CatalogsApi object instance.
     * @property {module:api/CatalogsApi}
     */
    Catalogs,

    /**
    * The ClientApi service constructor.
    * @property {module:api/ClientApi}
    */
    ClientApi,

    /**
     * The ClientApi object instance.
     * @property {module:api/ClientApi}
     */
    Client,

    /**
    * The DataPrivacyApi service constructor.
    * @property {module:api/DataPrivacyApi}
    */
    DataPrivacyApi,

    /**
     * The DataPrivacyApi object instance.
     * @property {module:api/DataPrivacyApi}
     */
    DataPrivacy,

    /**
    * The EventsApi service constructor.
    * @property {module:api/EventsApi}
    */
    EventsApi,

    /**
     * The EventsApi object instance.
     * @property {module:api/EventsApi}
     */
    Events,

    /**
    * The FlowsApi service constructor.
    * @property {module:api/FlowsApi}
    */
    FlowsApi,

    /**
     * The FlowsApi object instance.
     * @property {module:api/FlowsApi}
     */
    Flows,

    /**
    * The ListsApi service constructor.
    * @property {module:api/ListsApi}
    */
    ListsApi,

    /**
     * The ListsApi object instance.
     * @property {module:api/ListsApi}
     */
    Lists,

    /**
    * The MetricsApi service constructor.
    * @property {module:api/MetricsApi}
    */
    MetricsApi,

    /**
     * The MetricsApi object instance.
     * @property {module:api/MetricsApi}
     */
    Metrics,

    /**
    * The ProfilesApi service constructor.
    * @property {module:api/ProfilesApi}
    */
    ProfilesApi,

    /**
     * The ProfilesApi object instance.
     * @property {module:api/ProfilesApi}
     */
    Profiles,

    /**
    * The SegmentsApi service constructor.
    * @property {module:api/SegmentsApi}
    */
    SegmentsApi,

    /**
     * The SegmentsApi object instance.
     * @property {module:api/SegmentsApi}
     */
    Segments,

    /**
    * The TagsApi service constructor.
    * @property {module:api/TagsApi}
    */
    TagsApi,

    /**
     * The TagsApi object instance.
     * @property {module:api/TagsApi}
     */
    Tags,

    /**
    * The TemplatesApi service constructor.
    * @property {module:api/TemplatesApi}
    */
    TemplatesApi,

    /**
     * The TemplatesApi object instance.
     * @property {module:api/TemplatesApi}
     */
    Templates,

    /**
     * The SegmentsApi object instance.
     * @return {ApiClient#instance} a instance of {@link  module:ApiClient#instance}
     * */
    ConfigWrapper,
};
